import LRA.AlgebraicStructures.Semigroup.Examples.PositiveIntegersUnderAddition
import LRA.AlgebraicStructures.Semigroup.Examples.EvenIntegersUnderMultiplication
import LRA.AlgebraicStructures.Semigroup.Examples.NonemptyListsUnderConcatenation
import LRA.AlgebraicStructures.Semigroup.Examples.IdentityNotRequired
