import LRA.VolumeI.Set.ZFC.Model.Model

namespace LRA.VolumeI.Set

universe u

/-!
The primitive set layer.

There are two deliberately separate notions here:

* `ModelSet model`: an actual set-object inside a chosen first-order model of
  the ZFC signature.
* `LRASet alpha`: a Lean predicate over a carrier, used as the ambient
  meta-language for subsets, classes, and later induction predicates.

The first is the book-facing set object. The second is the proof-engineering
view needed to talk about collections of objects.
-/

/-- A set-theoretic universe is a model of the ZFC signature. -/
abbrev SetModel := LRA.VolumeI.Set.ZFC.ZFCModel

/-- A set in a model is an element of that model's domain. -/
abbrev ModelSet (model : SetModel) := model.Domain

namespace ModelSet

/-- Model-internal membership, interpreted by the model's `∈` relation. -/
def member {model : SetModel} (element set : ModelSet model) : Prop :=
  model.interpretRelation .member (fun index =>
    if index.val = 0 then element else set)

end ModelSet

/-- The project-level name for an arbitrary Lean carrier type. -/
abbrev LRACarrier := Type u

/-- A predicate-set, used for external collections over a chosen carrier. -/
abbrev LRASet (alpha : LRACarrier) := alpha -> Prop

/-- Short compatibility name for `LRACarrier`. -/
abbrev Carrier := LRACarrier

/-- Short compatibility name for predicate-sets. -/
abbrev Set := LRASet

/-- An indexed family of predicate-sets. -/
abbrev SetFamily (index : LRACarrier) (alpha : LRACarrier) :=
  index -> LRASet alpha

namespace LRASet

/-- Membership in a project predicate-set. -/
def member {alpha : LRACarrier} (element : alpha) (subset : LRASet alpha) : Prop :=
  subset element

/-- The empty predicate-set. -/
def empty (alpha : LRACarrier) : LRASet alpha :=
  fun _ => False

/-- The universal predicate-set. -/
def universal (alpha : LRACarrier) : LRASet alpha :=
  fun _ => True

/-- The singleton predicate-set generated by one element. -/
def singleton {alpha : LRACarrier} (element : alpha) : LRASet alpha :=
  fun candidate => candidate = element

/-- Binary union of predicate-sets. -/
def union {alpha : LRACarrier} (left right : LRASet alpha) : LRASet alpha :=
  fun element => member element left \/ member element right

/-- Binary intersection of predicate-sets. -/
def intersection {alpha : LRACarrier} (left right : LRASet alpha) : LRASet alpha :=
  fun element => member element left /\ member element right

/-- Complement of a predicate-set. -/
def complement {alpha : LRACarrier} (subset : LRASet alpha) : LRASet alpha :=
  fun element => Not (member element subset)

/-- Set difference of predicate-sets. -/
def difference {alpha : LRACarrier} (left right : LRASet alpha) : LRASet alpha :=
  fun element => member element left /\ Not (member element right)

/-- Subset relation for predicate-sets. -/
def subset {alpha : LRACarrier} (left right : LRASet alpha) : Prop :=
  forall element, member element left -> member element right

/-- Nonemptiness of a predicate-set. -/
def nonempty {alpha : LRACarrier} (subset : LRASet alpha) : Prop :=
  exists element, member element subset

/-- Indexed union of predicate-sets. -/
def indexedUnion {index alpha : LRACarrier} (family : SetFamily index alpha) :
    LRASet alpha :=
  fun element => exists i, member element (family i)

/-- Indexed intersection of predicate-sets. -/
def indexedIntersection {index alpha : LRACarrier} (family : SetFamily index alpha) :
    LRASet alpha :=
  fun element => forall i, member element (family i)

/-- Extensionality for predicate-sets. -/
theorem extensionality {alpha : LRACarrier} {left right : LRASet alpha}
    (sameMembers : forall element, member element left <-> member element right) :
    left = right := by
  funext element
  exact propext (sameMembers element)

end LRASet

end LRA.VolumeI.Set

