import LRA.VolumeI.Set.ZFC.Model.Model

universe u

namespace LRA.VolumeI.Set
open LRA.VolumeI.Set

/-!
The primitive set layer.

There are two deliberately separate notions here:

* `ModelSet model`: an actual set-object inside a chosen first-order model of
  the ZFC signature.
* `LRASet alpha`: a Lean predicate over a carrier, used as the ambient
  meta-language for subsets, classes, and later induction predicates.

The first is the book-facing set object. The second is the proof-engineering
view needed to talk about collections of objects.
-/

/-- A set-theoretic universe is a model of the ZFC signature. -/
abbrev SetModel := LRA.VolumeI.Set.ZFC.ZFCModel

/-- A set in a model is an element of that model's domain. -/
abbrev ModelSet (model : SetModel) := model.Domain

end LRA.VolumeI.Set

namespace LRA.VolumeI.Set.ModelSet

open LRA.VolumeI.Set

/-- Model-internal membership, interpreted by the model's `∈` relation. -/
def Member {model : SetModel} (element set : ModelSet model) : Prop :=
  model.interpretRelation .member (fun index =>
    if index.val = 0 then element else set)

end LRA.VolumeI.Set.ModelSet

namespace LRA.VolumeI.Set
open LRA.VolumeI.Set

/-- The project-level name for an arbitrary Lean carrier type. -/
abbrev LRACarrier := Type u

/-- A predicate-set, used for external collections over a chosen carrier. -/
abbrev LRASet (alpha : LRACarrier) := alpha -> Prop

/-- Short compatibility name for `LRACarrier`. -/
abbrev Carrier := LRACarrier

/-- Short compatibility name for predicate-sets. -/
abbrev Set := LRASet

/-- An indexed family of predicate-sets. -/
abbrev SetFamily (index : LRACarrier) (alpha : LRACarrier) :=
  index -> LRASet alpha

end LRA.VolumeI.Set

namespace LRA.VolumeI.Set.LRASet

open LRA.VolumeI.Set

/-- Membership in a project predicate-set. -/
def Member {alpha : LRACarrier} (element : alpha) (subset : LRASet alpha) : Prop :=
  subset element

/-- The empty predicate-set. -/
def Empty (alpha : LRACarrier) : LRASet alpha :=
  fun _ => False

/-- The universal predicate-set. -/
def Universal (alpha : LRACarrier) : LRASet alpha :=
  fun _ => True

/-- The singleton predicate-set generated by one element. -/
def Singleton {alpha : LRACarrier} (element : alpha) : LRASet alpha :=
  fun candidate => candidate = element

/-- Binary union of predicate-sets. -/
def Union {alpha : LRACarrier} (left right : LRASet alpha) : LRASet alpha :=
  fun element => Member element left \/ Member element right

/-- Binary intersection of predicate-sets. -/
def Intersection {alpha : LRACarrier} (left right : LRASet alpha) : LRASet alpha :=
  fun element => Member element left /\ Member element right

/-- Complement of a predicate-set. -/
def Complement {alpha : LRACarrier} (subset : LRASet alpha) : LRASet alpha :=
  fun element => Not (Member element subset)

/-- Set difference of predicate-sets. -/
def Difference {alpha : LRACarrier} (left right : LRASet alpha) : LRASet alpha :=
  fun element => Member element left /\ Not (Member element right)

/-- Subset relation for predicate-sets. -/
def Subset {alpha : LRACarrier} (left right : LRASet alpha) : Prop :=
  forall element, Member element left -> Member element right

/-- Nonemptiness of a predicate-set. -/
def Nonempty {alpha : LRACarrier} (subset : LRASet alpha) : Prop :=
  exists element, Member element subset

/-- Indexed union of predicate-sets. -/
def IndexedUnion {index alpha : LRACarrier} (family : SetFamily index alpha) :
    LRASet alpha :=
  fun element => exists i, Member element (family i)

/-- Indexed intersection of predicate-sets. -/
def IndexedIntersection {index alpha : LRACarrier} (family : SetFamily index alpha) :
    LRASet alpha :=
  fun element => forall i, Member element (family i)

/-- Extensionality for predicate-sets. -/
theorem Extensionality {alpha : LRACarrier} {left right : LRASet alpha}
    (sameMembers : forall element, Member element left <-> Member element right) :
    left = right := by
  funext element
  exact propext (sameMembers element)

end LRA.VolumeI.Set.LRASet
