import LRA.VolumeI.Relations.Equivalence.EquivalenceClass

namespace LRA.VolumeI.Relations

universe u

/-- A partition of a generic carrier by indexed nonempty, covering, disjoint blocks. -/
structure Partition (interface : LRA.VolumeI.Set.SetInterface.{u, u}) where
  Index : Type u
  Block : Index -> interface.SetObject
  Covers : forall element : interface.Element,
    exists index, interface.member element (Block index)
  NonemptyBlocks : forall index,
    exists element, interface.member element (Block index)
  DisjointOrEqual :
    forall firstIndex secondIndex,
      (exists element,
        interface.member element (Block firstIndex) /\
          interface.member element (Block secondIndex)) ->
        Block firstIndex = Block secondIndex

/-- The partition generated by an equivalence relation. -/
def PartitionFromEquivalence
    (operations : LRA.VolumeI.Set.Operations.ComprehensionSetOperations.{u, u})
    (ambient : operations.SetObject)
    (relation : Endorelation operations.Element)
    (relationIsEquivalence : EquivalenceRelation relation) :
    Partition operations.toPublicSetOperations := by
  sorry

end LRA.VolumeI.Relations
