import LRA.VolumeI.Relations.Equivalence.EquivalenceClass

namespace LRA.VolumeI.Relations

universe u

/-- A partition of a carrier by indexed nonempty, covering, disjoint blocks. -/
structure Partition (Alpha : LRA.VolumeI.Set.LRACarrier) where
  Index : Type u
  block : Index -> LRA.VolumeI.Set.LRASet Alpha
  covers : forall element : Alpha, exists index, block index element
  nonemptyBlocks : forall index, LRA.VolumeI.Set.LRASet.Nonempty (block index)
  disjointOrEqual :
    forall firstIndex secondIndex,
      (exists element, block firstIndex element /\ block secondIndex element) ->
        block firstIndex = block secondIndex

/-- The partition generated by an equivalence relation. -/
def PartitionFromEquivalence {Alpha : LRA.VolumeI.Set.LRACarrier}
    (relation : Endorelation Alpha)
    (relationIsEquivalence : EquivalenceRelation relation) :
    Partition Alpha := by
  sorry

end LRA.VolumeI.Relations
