import LRA.VolumeI.Relations.Equivalence.EquivalenceClass

namespace LRA.Relation

open LRA.Set

universe u v

/-- A partition of a generic carrier by indexed nonempty, covering, disjoint
blocks. Generic over any set backend with membership.

Logical form:

```lean
structure Partition (Element : Type u) (SetObject : Type v)
    [Membership Element SetObject] where
  Index : Type u
  Block : Index -> SetObject
  Covers : forall element : Element,
    exists index, element ∈ Block index
  NonemptyBlocks : forall index,
    exists element : Element, element ∈ Block index
  DisjointOrEqual :
    forall firstIndex secondIndex,
      (exists element : Element,
        element ∈ Block firstIndex /\ element ∈ Block secondIndex) ->
        Block firstIndex = Block secondIndex
```
-/
structure Partition (Element : Type u) (SetObject : Type v)
    [Membership Element SetObject] where
  Index : Type u
  Block : Index -> SetObject
  Covers : forall element : Element,
    exists index, element ∈ Block index
  NonemptyBlocks : forall index,
    exists element : Element, element ∈ Block index
  DisjointOrEqual :
    forall firstIndex secondIndex,
      (exists element : Element,
        element ∈ Block firstIndex /\ element ∈ Block secondIndex) ->
        Block firstIndex = Block secondIndex

/-- The partition generated by an equivalence relation.

Logical form:

```lean
def PartitionFromEquivalence
    {Element : Type u} {SetObject : Type v}
    [Membership Element SetObject] [HasSeparation Element SetObject]
    [SeparationLaws Element SetObject] [ExtensionalityLaw Element SetObject]
    (ambient : SetObject)
    (relation : Endorelation Element)
    (relationIsEquivalence : EquivalenceRelation relation) :
    Partition Element SetObject
```
-/
def PartitionFromEquivalence
    {Element : Type u} {SetObject : Type v}
    [Membership Element SetObject] [HasSeparation Element SetObject]
    [SeparationLaws Element SetObject] [ExtensionalityLaw Element SetObject]
    (ambient : SetObject)
    (relation : Endorelation Element)
    (relationIsEquivalence : EquivalenceRelation relation) :
    Partition Element SetObject := by
  sorry

end LRA.Relation
