import LRA.AlgebraicStructures.OrderedSemiring.Examples.NaturalNumbers
import LRA.AlgebraicStructures.OrderedSemiring.Examples.NonNegativeReals
import LRA.AlgebraicStructures.OrderedSemiring.Examples.ExtendedReals
