import LRA.NumberSystems.PositiveNaturals.Interface.Signature.Definition
import LRA.NumberSystems.PositiveNaturals.Interface.ModelTheory.Model
import LRA.NumberSystems.PositiveNaturals.Interface.UniversalAlgebra
