universe u

namespace LRA.VolumeI.Set

/-!
Type-theory set core.

This is the fresh typed-set layer. A typed set over `Alpha` is a predicate on
`Alpha`; this layer is deliberately separate from the archived Enderton/ZFC
experiment in `Set.old`.
-/

/-- Project-level name for an arbitrary Lean carrier type. -/
abbrev LRACarrier := Type u

/-- A type-theory set over a carrier. -/
abbrev TTSet (Alpha : LRACarrier) := Alpha → Prop

/-- Compatibility name used by existing Volume I/II code. -/
abbrev LRASet := TTSet

/-- Compatibility name for carriers. -/
abbrev Carrier := LRACarrier

/-- Compatibility name for typed sets. -/
abbrev Set := LRASet

/-- An indexed family of typed sets. -/
abbrev SetFamily (Index : LRACarrier) (Alpha : LRACarrier) :=
  Index → LRASet Alpha

namespace TTSet

/-- Containment in container-first direction. -/
def Contains {Alpha : LRACarrier} (set : TTSet Alpha) (element : Alpha) : Prop :=
  set element

/-- Membership in element-first direction. -/
def Member {Alpha : LRACarrier} (element : Alpha) (set : TTSet Alpha) : Prop :=
  Contains set element

/-- Lean's `element ∈ set` notation for typed predicate-sets. -/
instance {Alpha : LRACarrier} : Membership Alpha (TTSet Alpha) where
  mem set element := Member element set

/-- The empty typed set. -/
def Empty (Alpha : LRACarrier) : TTSet Alpha :=
  fun _ => False

/-- The universal typed set over a carrier. -/
def Universal (Alpha : LRACarrier) : TTSet Alpha :=
  fun _ => True

/-- The singleton typed set generated by one element. -/
def Singleton {Alpha : LRACarrier} (element : Alpha) : TTSet Alpha :=
  fun candidate => candidate = element

/-- Binary union of typed sets. -/
def Union {Alpha : LRACarrier} (left right : TTSet Alpha) : TTSet Alpha :=
  fun element => Member element left ∨ Member element right

/-- Binary intersection of typed sets. -/
def Intersection {Alpha : LRACarrier} (left right : TTSet Alpha) : TTSet Alpha :=
  fun element => Member element left ∧ Member element right

/-- Complement of a typed set relative to its carrier. -/
def Complement {Alpha : LRACarrier} (set : TTSet Alpha) : TTSet Alpha :=
  fun element => ¬ Member element set

/-- Set difference of typed sets. -/
def Difference {Alpha : LRACarrier} (left right : TTSet Alpha) : TTSet Alpha :=
  fun element => Member element left ∧ ¬ Member element right

/-- Subset relation for typed sets. -/
def Subset {Alpha : LRACarrier} (left right : TTSet Alpha) : Prop :=
  ∀ element, Member element left → Member element right

/-- Nonemptiness of a typed set. -/
def Nonempty {Alpha : LRACarrier} (set : TTSet Alpha) : Prop :=
  ∃ element, Member element set

/-- Indexed union of typed sets. -/
def IndexedUnion {Index Alpha : LRACarrier} (family : SetFamily Index Alpha) :
    TTSet Alpha :=
  fun element => ∃ index, Member element (family index)

/-- Indexed intersection of typed sets. -/
def IndexedIntersection {Index Alpha : LRACarrier} (family : SetFamily Index Alpha) :
    TTSet Alpha :=
  fun element => ∀ index, Member element (family index)

/-- Extensionality for typed sets. -/
theorem Extensionality {Alpha : LRACarrier} {left right : TTSet Alpha}
    (sameMembers : ∀ element, Member element left ↔ Member element right) :
    left = right := by
  sorry

end TTSet

namespace LRASet

def Contains {Alpha : LRACarrier} (set : LRASet Alpha) (element : Alpha) : Prop :=
  TTSet.Contains set element

def Member {Alpha : LRACarrier} (element : Alpha) (set : LRASet Alpha) : Prop :=
  TTSet.Member element set

def Empty (Alpha : LRACarrier) : LRASet Alpha :=
  TTSet.Empty Alpha

def Universal (Alpha : LRACarrier) : LRASet Alpha :=
  TTSet.Universal Alpha

def Singleton {Alpha : LRACarrier} (element : Alpha) : LRASet Alpha :=
  TTSet.Singleton element

def Union {Alpha : LRACarrier} (left right : LRASet Alpha) : LRASet Alpha :=
  TTSet.Union left right

def Intersection {Alpha : LRACarrier} (left right : LRASet Alpha) : LRASet Alpha :=
  TTSet.Intersection left right

def Complement {Alpha : LRACarrier} (set : LRASet Alpha) : LRASet Alpha :=
  TTSet.Complement set

def Difference {Alpha : LRACarrier} (left right : LRASet Alpha) : LRASet Alpha :=
  TTSet.Difference left right

def Subset {Alpha : LRACarrier} (left right : LRASet Alpha) : Prop :=
  TTSet.Subset left right

def Nonempty {Alpha : LRACarrier} (set : LRASet Alpha) : Prop :=
  TTSet.Nonempty set

def IndexedUnion {Index Alpha : LRACarrier} (family : SetFamily Index Alpha) :
    LRASet Alpha :=
  TTSet.IndexedUnion family

def IndexedIntersection {Index Alpha : LRACarrier} (family : SetFamily Index Alpha) :
    LRASet Alpha :=
  TTSet.IndexedIntersection family

theorem Extensionality {Alpha : LRACarrier} {left right : LRASet Alpha}
    (sameMembers : ∀ element, Member element left ↔ Member element right) :
    left = right := by
  sorry

end LRASet

end LRA.VolumeI.Set
