import LRA.AlgebraicStructures.OrderedGroup.Interface.ModelTheory.Theory
import LRA.AlgebraicStructures.OrderedGroup.Interface.ModelTheory.LStructure

namespace LRA.AlgebraicStructures.OrderedGroup.Interface.ModelTheory

end LRA.AlgebraicStructures.OrderedGroup.Interface.ModelTheory
