import LRA.AlgebraicStructures.DivisionRing.Interface.ModelTheory.Theory
import LRA.AlgebraicStructures.DivisionRing.Interface.ModelTheory.LStructure

namespace LRA.AlgebraicStructures.DivisionRing.Interface.ModelTheory

end LRA.AlgebraicStructures.DivisionRing.Interface.ModelTheory
