import LRA.AlgebraicStructures.DivisionRing.Interface.Definitions.Signature

namespace LRA.AlgebraicStructures.DivisionRing.Interface.ModelTheory

end LRA.AlgebraicStructures.DivisionRing.Interface.ModelTheory
