import LRA.Operation
import LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.WellFoundedness
import LRA.NumberSystems.PeanoSystem.Recursion.BinaryIterator

namespace LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann

open LRA.NumberSystems.PeanoSystem.Recursion

/-- The von Neumann one is the successor of the empty-set zero. -/
noncomputable def NaturalOne : NaturalElement :=
  NaturalSuccessor NaturalZero

/-- The 0-based von Neumann addition is generated by Peano recursion on the
concrete `VonNeumannPeanoSystem`. -/
noncomputable def VonNeumannAddition :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun left => left)
      (fun _ value => NaturalSuccessor value))

theorem VonNeumannAdditionClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun left => left)
      (fun _ value => NaturalSuccessor value)
      VonNeumannAddition := by
  sorry

theorem VonNeumannAdditionWellDefined :
    ∃ addition : NaturalElement → NaturalElement → NaturalElement,
      BinaryIteratorOperationClauses
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun left => left)
        (fun _ value => NaturalSuccessor value)
        addition ∧
      ∀ otherAddition : NaturalElement → NaturalElement → NaturalElement,
        BinaryIteratorOperationClauses
          VonNeumannPeanoSystem
          NaturalElement
          NaturalElement
          (fun left => left)
          (fun _ value => NaturalSuccessor value)
          otherAddition →
        otherAddition = addition := by
  sorry

theorem VonNeumannAdditionWithZero
    (left : NaturalElement) :
    VonNeumannAddition left NaturalZero = left := by
  sorry

theorem VonNeumannAdditionSuccessorOnRight
    (left right : NaturalElement) :
    VonNeumannAddition left (NaturalSuccessor right) =
      NaturalSuccessor (VonNeumannAddition left right) := by
  sorry

theorem VonNeumannAdditionIsAssociative :
    LRA.Operation.Laws.Associative.Associative
      VonNeumannAddition := by
  sorry

theorem VonNeumannAdditionIsCommutative :
    LRA.Operation.Laws.Commutative.Commutative
      VonNeumannAddition := by
  sorry

/-- The 0-based von Neumann multiplication is generated by repeated addition. -/
noncomputable def VonNeumannMultiplication :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalZero)
      (fun left value => VonNeumannAddition value left))

theorem VonNeumannMultiplicationClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalZero)
      (fun left value => VonNeumannAddition value left)
      VonNeumannMultiplication := by
  sorry

theorem VonNeumannMultiplicationWellDefined :
    ∃ multiplication : NaturalElement → NaturalElement → NaturalElement,
      BinaryIteratorOperationClauses
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun _ => NaturalZero)
        (fun left value => VonNeumannAddition value left)
        multiplication ∧
      ∀ otherMultiplication : NaturalElement → NaturalElement → NaturalElement,
        BinaryIteratorOperationClauses
          VonNeumannPeanoSystem
          NaturalElement
          NaturalElement
          (fun _ => NaturalZero)
          (fun left value => VonNeumannAddition value left)
          otherMultiplication →
        otherMultiplication = multiplication := by
  sorry

theorem VonNeumannMultiplicationWithZero
    (left : NaturalElement) :
    VonNeumannMultiplication left NaturalZero = NaturalZero := by
  sorry

theorem VonNeumannMultiplicationWithOne
    (left : NaturalElement) :
    VonNeumannMultiplication left NaturalOne = left := by
  sorry

theorem VonNeumannMultiplicationSuccessorOnRight
    (left right : NaturalElement) :
    VonNeumannMultiplication left (NaturalSuccessor right) =
      VonNeumannAddition (VonNeumannMultiplication left right) left := by
  sorry

theorem VonNeumannMultiplicationIsAssociative :
    LRA.Operation.Laws.Associative.Associative
      VonNeumannMultiplication := by
  sorry

theorem VonNeumannMultiplicationIsCommutative :
    LRA.Operation.Laws.Commutative.Commutative
      VonNeumannMultiplication := by
  sorry

theorem VonNeumannMultiplicationDistributesOverAddition :
    LRA.Operation.Laws.Distributive.RightDistributive
      VonNeumannMultiplication
      VonNeumannAddition := by
  sorry

theorem VonNeumannLeftDistributivityOfMultiplicationOverAddition :
    LRA.Operation.Laws.Distributive.LeftDistributive
      VonNeumannMultiplication
      VonNeumannAddition := by
  sorry

/-- The 0-based von Neumann exponentiation is generated by repeated
multiplication. -/
noncomputable def VonNeumannExponentiation :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalOne)
      (fun base value => VonNeumannMultiplication value base))

theorem VonNeumannExponentiationClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalOne)
      (fun base value => VonNeumannMultiplication value base)
      VonNeumannExponentiation := by
  sorry

end LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann
