import LRA.Operation
import LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.WellFoundedness
import LRA.NumberSystems.PeanoSystem.Recursion.BinaryIterator

namespace LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann

open LRA.NumberSystems.PeanoSystem.Recursion

/--
`NaturalOne` The von Neumann one is the successor of the empty-set zero.

Predicate logic:

  noncomputable def NaturalOne : NaturalElement :=
    NaturalSuccessor NaturalZero

Predicate logic (unfolded):

  noncomputable def NaturalOne : NaturalElement :=
    NaturalSuccessor NaturalZero (source fallback; no compiled unfold data available)

Logical form (Lean):

```lean
noncomputable def NaturalOne : NaturalElement :=
  NaturalSuccessor NaturalZero
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: unfold

-/
noncomputable def NaturalOne : NaturalElement :=
  NaturalSuccessor NaturalZero

/--
`VonNeumannAddition` The 0-based von Neumann addition is generated by Peano recursion on the concrete `VonNeumannPeanoSystem`.

Predicate logic:

  noncomputable def VonNeumannAddition :
      NaturalElement → NaturalElement → NaturalElement :=
    Classical.choose
      (ExistenceOfBinaryIteratorOperation
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun left => left)
        (fun _ value => NaturalSuccessor value))

Predicate logic (unfolded):

  noncomputable def VonNeumannAddition :
      NaturalElement → NaturalElement → NaturalElement :=
    Classical.choose
      (ExistenceOfBinaryIteratorOperation
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun left => left)
        (fun _ value => NaturalSuccessor value)) (source fallback; no compiled unfold data available)

Logical form (Lean):

```lean
noncomputable def VonNeumannAddition :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun left => left)
      (fun _ value => NaturalSuccessor value))
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: intro, unfold

-/
noncomputable def VonNeumannAddition :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun left => left)
      (fun _ value => NaturalSuccessor value))

/--
`VonNeumannAdditionClauses` TODO

Predicate logic:

  LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) (fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 parameterValue LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.1 = (fun left => left) parameterValue ∧ (∀ (element : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 parameterValue (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.2 element) = (fun x value => ⟨Classical.choose ⋯, ⋯⟩) parameterValue ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 parameterValue element)))

Logical form (Lean):

```lean
theorem VonNeumannAdditionClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun left => left)
      (fun _ value => NaturalSuccessor value)
      VonNeumannAddition
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannAdditionClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun left => left)
      (fun _ value => NaturalSuccessor value)
      VonNeumannAddition := by
  sorry
/--
`VonNeumannAdditionWellDefined` TODO

Predicate logic:

  Exists fun addition => (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) (fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) addition ∧ (∀ (otherAddition : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement → LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement → LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) (fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) otherAddition → otherAddition = addition))

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    Exists fun addition => ((∀ (parameterValue : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (addition parameterValue LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.1 = (fun left => left) parameterValue ∧ (∀ (element : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), addition parameterValue (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.2 element) = (fun x value => ⟨Classical.choose ⋯, ⋯⟩) parameterValue (addition parameterValue element)))) ∧ (∀ (otherAddition : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement → LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement → LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (∀ (parameterValue : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (otherAddition parameterValue LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.1 = (fun left => left) parameterValue ∧ (∀ (element : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), otherAddition parameterValue (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.2 element) = (fun x value => ⟨Classical.choose ⋯, ⋯⟩) parameterValue (otherAddition parameterValue element)))) → otherAddition = addition))

Logical form (Lean):

```lean
theorem VonNeumannAdditionWellDefined :
    ∃ addition : NaturalElement → NaturalElement → NaturalElement,
      BinaryIteratorOperationClauses
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun left => left)
        (fun _ value => NaturalSuccessor value)
        addition ∧
      ∀ otherAddition : NaturalElement → NaturalElement → NaturalElement,
        BinaryIteratorOperationClauses
          VonNeumannPeanoSystem
          NaturalElement
          NaturalElement
          (fun left => left)
          (fun _ value => NaturalSuccessor value)
          otherAddition →
        otherAddition = addition
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: intro, constructor, cases, rcases, use

-/
theorem VonNeumannAdditionWellDefined :
    ∃ addition : NaturalElement → NaturalElement → NaturalElement,
      BinaryIteratorOperationClauses
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun left => left)
        (fun _ value => NaturalSuccessor value)
        addition ∧
      ∀ otherAddition : NaturalElement → NaturalElement → NaturalElement,
        BinaryIteratorOperationClauses
          VonNeumannPeanoSystem
          NaturalElement
          NaturalElement
          (fun left => left)
          (fun _ value => NaturalSuccessor value)
          otherAddition →
        otherAddition = addition := by
  sorry
/--
`VonNeumannAdditionWithZero` TODO

Predicate logic:

  ∀ (left : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition left LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero = left

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    left : NaturalElement
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 left LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero = left

Logical form (Lean):

```lean
theorem VonNeumannAdditionWithZero
    (left : NaturalElement) :
    VonNeumannAddition left NaturalZero = left
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannAdditionWithZero
    (left : NaturalElement) :
    VonNeumannAddition left NaturalZero = left := by
  sorry
/--
`VonNeumannAdditionSuccessorOnRight` TODO

Predicate logic:

  ∀ (left right : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition left (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor right) = LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition left right)

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    left right : NaturalElement
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 left ⟨LRA.Set.Constructions.ZFCSet.Axioms.TheUnionOver (LRA.Set.Constructions.ZFCSet.Axioms.PairSet right.val (LRA.Set.Constructions.ZFCSet.Axioms.TheSingleton right.val)), ⋯⟩ = ⟨(Classical.indefiniteDescription (LRA.Set.Constructions.ZFCSet.Axioms.IsUnionOf (LRA.Set.Constructions.ZFCSet.Axioms.PairSet (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition left right).val (LRA.Set.Constructions.ZFCSet.Axioms.TheSingleton (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition left right).val))) ⋯).1, ⋯⟩

Logical form (Lean):

```lean
theorem VonNeumannAdditionSuccessorOnRight
    (left right : NaturalElement) :
    VonNeumannAddition left (NaturalSuccessor right) =
      NaturalSuccessor (VonNeumannAddition left right)
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannAdditionSuccessorOnRight
    (left right : NaturalElement) :
    VonNeumannAddition left (NaturalSuccessor right) =
      NaturalSuccessor (VonNeumannAddition left right) := by
  sorry
/--
`VonNeumannAdditionIsAssociative` TODO

Predicate logic:

  LRA.Operation.Laws.Associative.Associative LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).val first second) third = (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 first ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).val second third)

Logical form (Lean):

```lean
theorem VonNeumannAdditionIsAssociative :
    LRA.Operation.Laws.Associative.Associative
      VonNeumannAddition
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannAdditionIsAssociative :
    LRA.Operation.Laws.Associative.Associative
      VonNeumannAddition := by
  sorry
/--
`VonNeumannAdditionIsCommutative` TODO

Predicate logic:

  LRA.Operation.Laws.Commutative.Commutative LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 first second = (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 second first

Logical form (Lean):

```lean
theorem VonNeumannAdditionIsCommutative :
    LRA.Operation.Laws.Commutative.Commutative
      VonNeumannAddition
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannAdditionIsCommutative :
    LRA.Operation.Laws.Commutative.Commutative
      VonNeumannAddition := by
  sorry
/--
`VonNeumannMultiplication` The 0-based von Neumann multiplication is generated by repeated addition.

Predicate logic:

  noncomputable def VonNeumannMultiplication :
      NaturalElement → NaturalElement → NaturalElement :=
    Classical.choose
      (ExistenceOfBinaryIteratorOperation
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun _ => NaturalZero)
        (fun left value => VonNeumannAddition value left))

Predicate logic (unfolded):

  noncomputable def VonNeumannMultiplication :
      NaturalElement → NaturalElement → NaturalElement :=
    Classical.choose
      (ExistenceOfBinaryIteratorOperation
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun _ => NaturalZero)
        (fun left value => VonNeumannAddition value left)) (source fallback; no compiled unfold data available)

Logical form (Lean):

```lean
noncomputable def VonNeumannMultiplication :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalZero)
      (fun left value => VonNeumannAddition value left))
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: intro, unfold

-/
noncomputable def VonNeumannMultiplication :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalZero)
      (fun left value => VonNeumannAddition value left))

/--
`VonNeumannMultiplicationClauses` TODO

Predicate logic:

  LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) (fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 parameterValue LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.1 = (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) parameterValue ∧ (∀ (element : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 parameterValue (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.2 element) = (fun left value => (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 value left) parameterValue ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 parameterValue element)))

Logical form (Lean):

```lean
theorem VonNeumannMultiplicationClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalZero)
      (fun left value => VonNeumannAddition value left)
      VonNeumannMultiplication
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannMultiplicationClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalZero)
      (fun left value => VonNeumannAddition value left)
      VonNeumannMultiplication := by
  sorry
/--
`VonNeumannMultiplicationWellDefined` TODO

Predicate logic:

  Exists fun multiplication => (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) (fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) multiplication ∧ (∀ (otherMultiplication : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement → LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement → LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) (fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) otherMultiplication → otherMultiplication = multiplication))

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    Exists fun multiplication => ((∀ (parameterValue : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (multiplication parameterValue LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.1 = (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) parameterValue ∧ (∀ (element : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), multiplication parameterValue (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.2 element) = (fun left value => (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 value left) parameterValue (multiplication parameterValue element)))) ∧ (∀ (otherMultiplication : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement → LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement → LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (∀ (parameterValue : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (otherMultiplication parameterValue LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.1 = (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) parameterValue ∧ (∀ (element : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), otherMultiplication parameterValue (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.2 element) = (fun left value => (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 value left) parameterValue (otherMultiplication parameterValue element)))) → otherMultiplication = multiplication))

Logical form (Lean):

```lean
theorem VonNeumannMultiplicationWellDefined :
    ∃ multiplication : NaturalElement → NaturalElement → NaturalElement,
      BinaryIteratorOperationClauses
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun _ => NaturalZero)
        (fun left value => VonNeumannAddition value left)
        multiplication ∧
      ∀ otherMultiplication : NaturalElement → NaturalElement → NaturalElement,
        BinaryIteratorOperationClauses
          VonNeumannPeanoSystem
          NaturalElement
          NaturalElement
          (fun _ => NaturalZero)
          (fun left value => VonNeumannAddition value left)
          otherMultiplication →
        otherMultiplication = multiplication
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: intro, constructor, cases, rcases, use

-/
theorem VonNeumannMultiplicationWellDefined :
    ∃ multiplication : NaturalElement → NaturalElement → NaturalElement,
      BinaryIteratorOperationClauses
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun _ => NaturalZero)
        (fun left value => VonNeumannAddition value left)
        multiplication ∧
      ∀ otherMultiplication : NaturalElement → NaturalElement → NaturalElement,
        BinaryIteratorOperationClauses
          VonNeumannPeanoSystem
          NaturalElement
          NaturalElement
          (fun _ => NaturalZero)
          (fun left value => VonNeumannAddition value left)
          otherMultiplication →
        otherMultiplication = multiplication := by
  sorry
/--
`VonNeumannMultiplicationWithZero` TODO

Predicate logic:

  ∀ (left : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication left LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero = LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    left : NaturalElement
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 left LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero = LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero

Logical form (Lean):

```lean
theorem VonNeumannMultiplicationWithZero
    (left : NaturalElement) :
    VonNeumannMultiplication left NaturalZero = NaturalZero
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannMultiplicationWithZero
    (left : NaturalElement) :
    VonNeumannMultiplication left NaturalZero = NaturalZero := by
  sorry
/--
`VonNeumannMultiplicationWithOne` TODO

Predicate logic:

  ∀ (left : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication left LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalOne = left

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    left : NaturalElement
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 left LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalOne = left

Logical form (Lean):

```lean
theorem VonNeumannMultiplicationWithOne
    (left : NaturalElement) :
    VonNeumannMultiplication left NaturalOne = left
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannMultiplicationWithOne
    (left : NaturalElement) :
    VonNeumannMultiplication left NaturalOne = left := by
  sorry
/--
`VonNeumannMultiplicationSuccessorOnRight` TODO

Predicate logic:

  ∀ (left right : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication left (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor right) = LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication left right) left

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    left right : NaturalElement
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 left ⟨LRA.Set.Constructions.ZFCSet.Axioms.TheUnionOver (LRA.Set.Constructions.ZFCSet.Axioms.PairSet right.val (LRA.Set.Constructions.ZFCSet.Axioms.TheSingleton right.val)), ⋯⟩ = (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 left right) left

Logical form (Lean):

```lean
theorem VonNeumannMultiplicationSuccessorOnRight
    (left right : NaturalElement) :
    VonNeumannMultiplication left (NaturalSuccessor right) =
      VonNeumannAddition (VonNeumannMultiplication left right) left
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannMultiplicationSuccessorOnRight
    (left right : NaturalElement) :
    VonNeumannMultiplication left (NaturalSuccessor right) =
      VonNeumannAddition (VonNeumannMultiplication left right) left := by
  sorry
/--
`VonNeumannMultiplicationIsAssociative` TODO

Predicate logic:

  LRA.Operation.Laws.Associative.Associative LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).val first second) third = (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 first ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).val second third)

Logical form (Lean):

```lean
theorem VonNeumannMultiplicationIsAssociative :
    LRA.Operation.Laws.Associative.Associative
      VonNeumannMultiplication
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannMultiplicationIsAssociative :
    LRA.Operation.Laws.Associative.Associative
      VonNeumannMultiplication := by
  sorry
/--
`VonNeumannMultiplicationIsCommutative` TODO

Predicate logic:

  LRA.Operation.Laws.Commutative.Commutative LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 first second = (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 second first

Logical form (Lean):

```lean
theorem VonNeumannMultiplicationIsCommutative :
    LRA.Operation.Laws.Commutative.Commutative
      VonNeumannMultiplication
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannMultiplicationIsCommutative :
    LRA.Operation.Laws.Commutative.Commutative
      VonNeumannMultiplication := by
  sorry
/--
`VonNeumannMultiplicationDistributesOverAddition` TODO

Predicate logic:

  LRA.Operation.Laws.Distributive.RightDistributive LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).val left right) third = (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).val left third) ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).val right third)

Logical form (Lean):

```lean
theorem VonNeumannMultiplicationDistributesOverAddition :
    LRA.Operation.Laws.Distributive.RightDistributive
      VonNeumannMultiplication
      VonNeumannAddition
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannMultiplicationDistributesOverAddition :
    LRA.Operation.Laws.Distributive.RightDistributive
      VonNeumannMultiplication
      VonNeumannAddition := by
  sorry
/--
`VonNeumannLeftDistributivityOfMultiplicationOverAddition` TODO

Predicate logic:

  LRA.Operation.Laws.Distributive.LeftDistributive LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 left ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).val right third) = (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun left => left) fun x value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalSuccessor value) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition._proof_1).1 ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).val left right) ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).val left third)

Logical form (Lean):

```lean
theorem VonNeumannLeftDistributivityOfMultiplicationOverAddition :
    LRA.Operation.Laws.Distributive.LeftDistributive
      VonNeumannMultiplication
      VonNeumannAddition
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannLeftDistributivityOfMultiplicationOverAddition :
    LRA.Operation.Laws.Distributive.LeftDistributive
      VonNeumannMultiplication
      VonNeumannAddition := by
  sorry
/--
`VonNeumannExponentiation` The 0-based von Neumann exponentiation is generated by repeated multiplication.

Predicate logic:

  noncomputable def VonNeumannExponentiation :
      NaturalElement → NaturalElement → NaturalElement :=
    Classical.choose
      (ExistenceOfBinaryIteratorOperation
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun _ => NaturalOne)
        (fun base value => VonNeumannMultiplication value base))

Predicate logic (unfolded):

  noncomputable def VonNeumannExponentiation :
      NaturalElement → NaturalElement → NaturalElement :=
    Classical.choose
      (ExistenceOfBinaryIteratorOperation
        VonNeumannPeanoSystem
        NaturalElement
        NaturalElement
        (fun _ => NaturalOne)
        (fun base value => VonNeumannMultiplication value base)) (source fallback; no compiled unfold data available)

Logical form (Lean):

```lean
noncomputable def VonNeumannExponentiation :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalOne)
      (fun base value => VonNeumannMultiplication value base))
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: intro, unfold

-/
noncomputable def VonNeumannExponentiation :
    NaturalElement → NaturalElement → NaturalElement :=
  Classical.choose
    (ExistenceOfBinaryIteratorOperation
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalOne)
      (fun base value => VonNeumannMultiplication value base))

/--
`VonNeumannExponentiationClauses` TODO

Predicate logic:

  LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalOne) (fun base value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication value base) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannExponentiation

Predicate logic (unfolded):

  Ambient
    (implicit ambient)
  Objects
    (none)
  Prove
    ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalOne) fun base value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication value base) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannExponentiation._proof_1).1 parameterValue LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.1 = (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalOne) parameterValue ∧ (∀ (element : LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement), (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalOne) fun base value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication value base) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannExponentiation._proof_1).1 parameterValue (LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem.2 element) = (fun base value => (Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalZero) fun left value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannAddition value left) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication._proof_1).1 value base) parameterValue ((Classical.indefiniteDescription (LRA.NumberSystems.PeanoSystem.Recursion.BinaryIteratorOperationClauses LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannPeanoSystem LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalElement (fun x => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.NaturalOne) fun base value => LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannMultiplication value base) LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann.VonNeumannExponentiation._proof_1).1 parameterValue element)))

Logical form (Lean):

```lean
theorem VonNeumannExponentiationClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalOne)
      (fun base value => VonNeumannMultiplication value base)
      VonNeumannExponentiation
```

Type-theoretic form:

  TODO

Proof use:

  TODO

After unfold / common proof state:

  TODO

Common confusions:

  TODO

Related proof moves: TODO

-/
theorem VonNeumannExponentiationClauses :
    BinaryIteratorOperationClauses
      VonNeumannPeanoSystem
      NaturalElement
      NaturalElement
      (fun _ => NaturalOne)
      (fun base value => VonNeumannMultiplication value base)
      VonNeumannExponentiation := by
  sorry
end LRA.NumberSystems.NaturalNumbers.Constructions.VonNeumann
