import LRA.AlgebraicStructures.CompleteOrderedField.Interface.Definitions
import LRA.AlgebraicStructures.CompleteOrderedField.Interface.ModelTheory
import LRA.AlgebraicStructures.CompleteOrderedField.Interface.Laws
