import LRA.AlgebraicStructures.CompleteOrderedField.Laws.Definition
import LRA.AlgebraicStructures.CompleteOrderedField.Laws.Theorems
import LRA.AlgebraicStructures.CompleteOrderedField.Laws.Characterizations
import LRA.AlgebraicStructures.CompleteOrderedField.Laws.Consequences
import LRA.AlgebraicStructures.CompleteOrderedField.Laws.Relationships
