import LRA.AlgebraicStructures.Semigroup.Interface.ModelTheory.LStructure
import LRA.AlgebraicStructures.Semigroup.Interface.ModelTheory.Theory
import LRA.AlgebraicStructures.Semigroup.Interface.ModelTheory.Model
