import LRA.Set.Constructions.TG.Extensionality.Theorems
import LRA.Set.Constructions.TG.EmptySet.Theorems
import LRA.Set.Constructions.TG.Pairing.Theorems
import LRA.Set.Constructions.TG.Union.Theorems
import LRA.Set.Constructions.TG.PowerSet.Theorems
import LRA.Set.Constructions.TG.Infinity.Theorems
import LRA.Set.Constructions.TG.Separation.Theorems
import LRA.Set.Constructions.TG.Replacement.Theorems
import LRA.Set.Constructions.TG.Foundation.Theorems
import LRA.Set.Constructions.TG.Choice.Theorems
import LRA.Set.Constructions.TG.GrothendieckUniverse.Theorems
import LRA.Set.Constructions.TG.OrderedPair.Theorems
import LRA.Set.Constructions.TG.Intersection.Theorems
import LRA.Set.Constructions.TG.RelativeComplement.Theorems
import LRA.Set.Constructions.TG.SymmetricDifference.Theorems
import LRA.Set.Constructions.TG.IntersectionOver.Theorems
