import LRA.VolumeI.Identity.Theory

universe u

namespace LRA.VolumeI.Set

/-!
Type-theory set core.

This is the fresh typed-set layer. A typed set over `Alpha` is a predicate on
`Alpha`; this layer is deliberately separate from the Enderton/ZFC backend.
-/

/-- Type-theory implementation carrier. -/
abbrev TTCarrier := Type u

/-- A type-theory set over a carrier. -/
abbrev TTSet (Alpha : TTCarrier) := Alpha → Prop

/-- An indexed family of typed sets. -/
abbrev SetFamily (Index : TTCarrier) (Alpha : TTCarrier) :=
  Index → TTSet Alpha

namespace TTSet

/-- Containment in container-first direction. -/
def Contains {Alpha : TTCarrier} (set : TTSet Alpha) (element : Alpha) : Prop :=
  set element

/-- Membership in element-first direction. -/
def Member {Alpha : TTCarrier} (element : Alpha) (set : TTSet Alpha) : Prop :=
  Contains set element

/-- Lean's `element ∈ set` notation for typed predicate-sets. -/
instance {Alpha : TTCarrier} : Membership Alpha (TTSet Alpha) where
  mem set element := Member element set

/-- The empty typed set. -/
def Empty (Alpha : TTCarrier) : TTSet Alpha :=
  fun _ => False

/-- There is a unique typed set with no members. This is the typed-set analogue
of the empty-set existence and uniqueness theorem. -/
theorem EmptySetExistsUnique (Alpha : TTCarrier) :
    LRA.VolumeI.Identity.ExistsAndUnique
      (fun empty : TTSet Alpha => ∀ element, ¬ Member element empty) := by
  sorry

/-- The universal typed set over a carrier. -/
def Universal (Alpha : TTCarrier) : TTSet Alpha :=
  fun _ => True

/-- The singleton typed set generated by one element. -/
def Singleton {Alpha : TTCarrier} (element : Alpha) : TTSet Alpha :=
  fun candidate => candidate = element

/-- Binary union of typed sets. -/
def Union {Alpha : TTCarrier} (left right : TTSet Alpha) : TTSet Alpha :=
  fun element => Member element left ∨ Member element right

/-- For any two typed sets, there is a unique typed set whose members are
exactly the elements belonging to the left set or the right set. -/
theorem BinaryUnionExistsUnique {Alpha : TTCarrier}
    (left right : TTSet Alpha) :
    LRA.VolumeI.Identity.ExistsAndUnique
      (fun unionSet : TTSet Alpha =>
        ∀ element,
          Member element unionSet ↔ Member element left ∨ Member element right) := by
  sorry

/-- For any two elements, there is a unique typed set whose members are exactly
those two elements. This is the typed-set analogue of the pairing-output
existence and uniqueness theorem. -/
theorem PairSetExistsUnique {Alpha : TTCarrier} (left right : Alpha) :
    LRA.VolumeI.Identity.ExistsAndUnique
      (fun pairSet : TTSet Alpha =>
        ∀ element, Member element pairSet ↔ element = left ∨ element = right) := by
  sorry

/-- Binary intersection of typed sets. -/
def Intersection {Alpha : TTCarrier} (left right : TTSet Alpha) : TTSet Alpha :=
  fun element => Member element left ∧ Member element right

/-- For any two typed sets, there is a unique typed set whose members are
exactly the elements belonging to both the left set and the right set. -/
theorem IntersectionExistsUnique {Alpha : TTCarrier}
    (left right : TTSet Alpha) :
    LRA.VolumeI.Identity.ExistsAndUnique
      (fun intersectionSet : TTSet Alpha =>
        ∀ element,
          Member element intersectionSet ↔
            Member element left ∧ Member element right) := by
  sorry

/-- Complement of a typed set relative to its carrier. -/
def Complement {Alpha : TTCarrier} (set : TTSet Alpha) : TTSet Alpha :=
  fun element => ¬ Member element set

/-- Set difference of typed sets. -/
def Difference {Alpha : TTCarrier} (left right : TTSet Alpha) : TTSet Alpha :=
  fun element => Member element left ∧ ¬ Member element right

/-- For any two typed sets, there is a unique typed set whose members are
exactly the elements belonging to the left set and not to the right set. -/
theorem DifferenceExistsUnique {Alpha : TTCarrier}
    (left right : TTSet Alpha) :
    LRA.VolumeI.Identity.ExistsAndUnique
      (fun differenceSet : TTSet Alpha =>
        ∀ element,
          Member element differenceSet ↔
            Member element left ∧ ¬ Member element right) := by
  sorry

/-- Complement of a typed set relative to a chosen ambient typed set. -/
def RelativeComplement {Alpha : TTCarrier}
    (ambient set : TTSet Alpha) : TTSet Alpha :=
  Difference ambient set

/-- For any ambient typed set and subset candidate, there is a unique typed set
whose members are exactly the ambient elements outside the candidate set. -/
theorem RelativeComplementExistsUnique {Alpha : TTCarrier}
    (ambient set : TTSet Alpha) :
    LRA.VolumeI.Identity.ExistsAndUnique
      (fun complementSet : TTSet Alpha =>
        ∀ element,
          Member element complementSet ↔
            Member element ambient ∧ ¬ Member element set) := by
  sorry

/-- Symmetric difference of typed sets: elements belonging to exactly one of
the two sets. -/
def SymmetricDifference {Alpha : TTCarrier}
    (left right : TTSet Alpha) : TTSet Alpha :=
  Union (Difference left right) (Difference right left)

/-- For any two typed sets, there is a unique typed set whose members belong to
exactly one of the two input sets. -/
theorem SymmetricDifferenceExistsUnique {Alpha : TTCarrier}
    (left right : TTSet Alpha) :
    LRA.VolumeI.Identity.ExistsAndUnique
      (fun symmetricDifferenceSet : TTSet Alpha =>
        ∀ element,
          Member element symmetricDifferenceSet ↔
            (Member element left ∧ ¬ Member element right) ∨
              (Member element right ∧ ¬ Member element left)) := by
  sorry

/-- Bounded typed-set comprehension: the subset of an ambient set whose members
satisfy a property. This is the typed-set analogue of Separation. -/
def Separation {Alpha : TTCarrier}
    (ambient : TTSet Alpha) (property : Alpha → Prop) : TTSet Alpha :=
  fun element => Member element ambient ∧ property element

/-- For any typed set and property, there is a unique typed set whose members
are exactly the members of the ambient set satisfying that property. -/
theorem SeparationExistsUnique {Alpha : TTCarrier}
    (ambient : TTSet Alpha) (property : Alpha → Prop) :
    LRA.VolumeI.Identity.ExistsAndUnique
      (fun separatedSet : TTSet Alpha =>
        ∀ element,
          Member element separatedSet ↔
            Member element ambient ∧ property element) := by
  sorry

/-- Subset relation for typed sets. -/
def Subset {Alpha : TTCarrier} (left right : TTSet Alpha) : Prop :=
  ∀ element, Member element left → Member element right

/-- Nonemptiness of a typed set. -/
def Nonempty {Alpha : TTCarrier} (set : TTSet Alpha) : Prop :=
  ∃ element, Member element set

/-- Indexed union of typed sets. -/
def IndexedUnion {Index Alpha : TTCarrier} (family : SetFamily Index Alpha) :
    TTSet Alpha :=
  fun element => ∃ index, Member element (family index)

/-- Indexed intersection of typed sets. -/
def IndexedIntersection {Index Alpha : TTCarrier} (family : SetFamily Index Alpha) :
    TTSet Alpha :=
  fun element => ∀ index, Member element (family index)

/-- Extensionality for typed sets. -/
theorem Extensionality {Alpha : TTCarrier} {left right : TTSet Alpha}
    (sameMembers : ∀ element, Member element left ↔ Member element right) :
    left = right := by
  sorry

end TTSet

end LRA.VolumeI.Set
