import LRA.AlgebraicStructures.Monoid.Examples.NaturalNumbersUnderAddition
import LRA.AlgebraicStructures.Monoid.Examples.NaturalNumbersUnderMultiplication
import LRA.AlgebraicStructures.Monoid.Examples.FreeMonoidOnWords
import LRA.AlgebraicStructures.Monoid.Examples.TransformationMonoid
import LRA.AlgebraicStructures.Monoid.Examples.SquareMatrices
