import LRA.UniversalAlgebra.Congruence.Definition
import LRA.UniversalAlgebra.Congruence.Theorems
import LRA.UniversalAlgebra.Congruence.Relationships
import LRA.UniversalAlgebra.Congruence.Consequences
