import LRA.AlgebraicStructures.CommutativeRing.Interface.ModelTheory.Theory
import LRA.AlgebraicStructures.CommutativeRing.Interface.ModelTheory.LStructure

namespace LRA.AlgebraicStructures.CommutativeRing.Interface.ModelTheory

end LRA.AlgebraicStructures.CommutativeRing.Interface.ModelTheory
