import LRA.AlgebraicStructures.CommutativeRing.Interface.Definitions.Signature

namespace LRA.AlgebraicStructures.CommutativeRing.Interface.ModelTheory

end LRA.AlgebraicStructures.CommutativeRing.Interface.ModelTheory
