import Mathlib.Algebra.Group.Nat.Defs
import LRA.AlgebraicStructures.AdditiveMonoid.Constructions.Mathlib.Laws

namespace LRA.AlgebraicStructures.AdditiveMonoid.Examples

/-- `(ℕ, +, 0)` — free directly on `Nat` itself: it already carries the
native `Add`/`OfNat _ 0` instances this subject's `AdditiveMonoidLaws` is
stated in terms of, and `Nat` is an `AddMonoid` in Mathlib, so this comes for
free via `Constructions/Mathlib/Laws.lean`'s generic bridge. Doubles as the
user's fifth standard example: the same structure, viewed as the free
additive monoid generated by `{1}` under repeated addition (every `n : ℕ` is
`1 + 1 + ⋯ + 1`, `n` times) — same carrier, same operation, no separate
construction needed. -/
example : LRA.AlgebraicStructures.AdditiveMonoidLaws Nat := inferInstance

end LRA.AlgebraicStructures.AdditiveMonoid.Examples
