import LRA.NumberSystems.SuccessorArithmetic.Constructions
import LRA.NumberSystems.NaturalNumbers.Constructions
import LRA.NumberSystems.WholeNumbers.Constructions
import LRA.NumberSystems.Integers.Constructions
import LRA.NumberSystems.RationalNumbers.Constructions
import LRA.NumberSystems.RealNumbers.Constructions
import LRA.NumberSystems.ComplexNumbers.Constructions
import LRA.NumberSystems.GaussianIntegers.Constructions
