import LRA.NumberSystems.SuccessorArithmetic.Examples
import LRA.NumberSystems.NaturalNumbers.Examples
import LRA.NumberSystems.WholeNumbers.Examples
import LRA.NumberSystems.Integers.Examples.NumberSystems
import LRA.NumberSystems.Integers.Examples
import LRA.NumberSystems.RationalNumbers.Examples.NumberSystems
import LRA.NumberSystems.RationalNumbers.Examples
import LRA.NumberSystems.RealNumbers.Examples
import LRA.NumberSystems.ComplexNumbers.Examples
import LRA.NumberSystems.GaussianIntegers.Examples
