import LRA.NumberSystems.Interface.ModelTheory.LStructure
import LRA.NumberSystems.Interface.ModelTheory.Theory
import LRA.NumberSystems.Interface.ModelTheory.Model
import LRA.NumberSystems.Interface.ModelTheory.CanonicalEmbeddings
import LRA.NumberSystems.Interface.ModelTheory.UniversalProperties
import LRA.NumberSystems.PeanoSystem.Interface.Signature.Definition
import LRA.NumberSystems.PeanoSystem.Interface.ModelTheory.LStructure
import LRA.NumberSystems.PeanoSystem.Interface.ModelTheory.Theory
import LRA.NumberSystems.PeanoSystem.Interface.ModelTheory.Model
import LRA.NumberSystems.NaturalNumbers.Interface.Signature.Definition
import LRA.NumberSystems.NaturalNumbers.Interface.ModelTheory.LStructure
import LRA.NumberSystems.NaturalNumbers.Interface.ModelTheory.Theory
import LRA.NumberSystems.NaturalNumbers.Interface.ModelTheory.Model
import LRA.NumberSystems.WholeNumbers.Interface.Signature.Definition
import LRA.NumberSystems.WholeNumbers.Interface.ModelTheory.LStructure
import LRA.NumberSystems.WholeNumbers.Interface.ModelTheory.Theory
import LRA.NumberSystems.WholeNumbers.Interface.ModelTheory.Model
import LRA.NumberSystems.IntegerStructure.Interface.Signature.Definition
import LRA.NumberSystems.IntegerStructure.Interface.ModelTheory.LStructure
import LRA.NumberSystems.IntegerStructure.Interface.ModelTheory.Theory
import LRA.NumberSystems.IntegerStructure.Interface.ModelTheory.Model
import LRA.NumberSystems.Integers.Interface.Signature.Definition
import LRA.NumberSystems.Integers.Interface.ModelTheory.LStructure
import LRA.NumberSystems.Integers.Interface.ModelTheory.Theory
import LRA.NumberSystems.Integers.Interface.ModelTheory.Model
import LRA.NumberSystems.RationalNumbers.Interface.Signature.Definition
import LRA.NumberSystems.RationalNumbers.Interface.ModelTheory.LStructure
import LRA.NumberSystems.RationalNumbers.Interface.ModelTheory.Theory
import LRA.NumberSystems.RationalNumbers.Interface.ModelTheory.Model
import LRA.NumberSystems.RealNumbers.Interface.Signature.Definition
import LRA.NumberSystems.RealNumbers.Interface.ModelTheory.LStructure
import LRA.NumberSystems.RealNumbers.Interface.ModelTheory.Theory
import LRA.NumberSystems.RealNumbers.Interface.ModelTheory.Model
import LRA.NumberSystems.ComplexNumbers.Interface.Signature.Definition
import LRA.NumberSystems.ComplexNumbers.Interface.ModelTheory.LStructure
import LRA.NumberSystems.ComplexNumbers.Interface.ModelTheory.Theory
import LRA.NumberSystems.ComplexNumbers.Interface.ModelTheory.Model
import LRA.NumberSystems.GaussianIntegers.Interface.Signature.Definition
import LRA.NumberSystems.GaussianIntegers.Interface.ModelTheory.LStructure
import LRA.NumberSystems.GaussianIntegers.Interface.ModelTheory.Theory
import LRA.NumberSystems.GaussianIntegers.Interface.ModelTheory.Model
