import LRA.AlgebraicStructures.OrderedField.Interface.ModelTheory.Theory
import LRA.AlgebraicStructures.OrderedField.Interface.ModelTheory.LStructure

namespace LRA.AlgebraicStructures.OrderedField.Interface.ModelTheory

end LRA.AlgebraicStructures.OrderedField.Interface.ModelTheory
