import LRA.AlgebraicStructures.OrderedField.Interface.Definitions.Signature

namespace LRA.AlgebraicStructures.OrderedField.Interface.ModelTheory

end LRA.AlgebraicStructures.OrderedField.Interface.ModelTheory
