
import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.Operations

namespace LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs

end LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs
