import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.Carrier
import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.Equivalence
import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.WellFoundedness
import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.Operations
import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.WellDefinedness
import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.Laws
import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.Behavior
import LRA.NumberSystems.GaussianIntegers.Constructions.OrderedPairs.Instances
