import LRA.VolumeI.Set.Algebra.SigmaAlgebra

namespace LRA.VolumeI.Set.Algebra

open LRA.VolumeI.Set

universe u v

/-!
Generated sigma-algebras, and the Borel construction.

Where the retired `BorelAlgebraSignature` merely *recorded* a generating
family, generation is now the definition: the sigma-algebra generated by
`generator` is the intersection of all sigma-algebras on the ambient set
that admit every generator -- so minimality is finally a statement, not
a promise. The Borel sigma-algebra of a topology is this construction
applied with the open sets as generator.
-/

variable {Element : Type u} {SetObject : Type v}
variable [Membership Element SetObject]
variable [Union SetObject] [Inter SetObject] [SDiff SetObject]
variable [EmptyCollection SetObject] [HasSubset SetObject]
variable [HasSymmDiff SetObject]
variable [HasCountableUnion SetObject]

/-- The collection underlying the generated sigma-algebra: a set belongs
to it exactly when every sigma-algebra on `ambient` admitting all
generators admits it. -/
def GeneratedSigmaAlgebraCollection
    (ambient : SetObject) (generator : SetObject → Prop) :
    SetObject → Prop :=
  fun A =>
    ∀ sigma : SigmaAlgebraOfSets ambient,
      (∀ G, generator G → sigma.IsMember G) → sigma.IsMember A

/-- The sigma-algebra generated by `generator` on `ambient`: the smallest
sigma-algebra admitting every generator. The closure fields are the
standard intersection argument, pending proof. -/
def GeneratedSigmaAlgebra
    (ambient : SetObject) (generator : SetObject → Prop) :
    SigmaAlgebraOfSets ambient where
  IsMember := GeneratedSigmaAlgebraCollection ambient generator
  MembersAreSubsets := by sorry
  EmptyIsMember := by sorry
  UnionIsMember := by sorry
  IntersectionIsMember := by sorry
  DifferenceIsMember := by sorry
  SymmetricDifferenceIsMember := by sorry
  AmbientIsMember := by sorry
  CountableUnionIsMember := by sorry

/-- Every subset-of-ambient generator is a member of the sigma-algebra it
generates. -/
theorem GeneratedSigmaAlgebraContainsGenerator
    (ambient : SetObject) (generator : SetObject → Prop)
    (G : SetObject) (GIsGenerator : generator G) :
    (GeneratedSigmaAlgebra ambient generator).IsMember G := by
  sorry

/-- Minimality: any sigma-algebra admitting the generators contains the
generated sigma-algebra. (Immediate from the definition -- the generated
collection is the intersection.) -/
theorem GeneratedSigmaAlgebraMinimal
    (ambient : SetObject) (generator : SetObject → Prop)
    (sigma : SigmaAlgebraOfSets ambient)
    (sigmaAdmitsGenerators : ∀ G, generator G → sigma.IsMember G) :
    ∀ A, (GeneratedSigmaAlgebra ambient generator).IsMember A →
      sigma.IsMember A := by
  sorry

/-- The Borel sigma-algebra on `ambient` determined by a family of open
sets: the sigma-algebra generated by the opens. -/
def BorelSigmaAlgebra
    (ambient : SetObject) (opens : SetObject → Prop) :
    SigmaAlgebraOfSets ambient :=
  GeneratedSigmaAlgebra ambient opens

end LRA.VolumeI.Set.Algebra
