import LRA.VolumeI.Set.Algebra.SigmaAlgebra

namespace LRA.Set.Algebra

open LRA.Set

universe u v

/-!
Generated sigma-algebras, and the Borel construction.

Where the retired `BorelAlgebraSignature` merely *recorded* a generating
family, generation is now the definition: the sigma-algebra generated by
`generator` is the intersection of all sigma-algebras on the ambient set
that admit every generator -- so minimality is finally a statement, not
a promise. The Borel sigma-algebra of a topology is this construction
applied with the open sets as generator.
-/

variable {Element : Type u} {SetObject : Type v}
variable [Membership Element SetObject]
variable [Union SetObject] [Inter SetObject] [SDiff SetObject]
variable [EmptyCollection SetObject] [HasSubset SetObject]
variable [HasSymmDiff SetObject]
variable [HasCountableUnion SetObject]

/-- The collection underlying the generated sigma-algebra: a set belongs
to it exactly when every sigma-algebra on `ambient` admitting all
generators admits it.

Logical form:

```lean
def GeneratedSigmaAlgebraCollection
    (ambient : SetObject) (generator : SetObject → Prop) :
    SetObject → Prop :=
  fun A =>
    ∀ sigma : SigmaAlgebraOfSets ambient,
      (∀ G, generator G → sigma.IsMember G) → sigma.IsMember A
```
-/
def GeneratedSigmaAlgebraCollection
    (ambient : SetObject) (generator : SetObject → Prop) :
    SetObject → Prop :=
  fun A =>
    ∀ sigma : SigmaAlgebraOfSets ambient,
      (∀ G, generator G → sigma.IsMember G) → sigma.IsMember A

/--
**[Theorem — Generated Sigma Algebra Members Are Subsets]** Every member of
the generated sigma-algebra is a subset of the ambient set.

Logical form:

```lean
∀ A, GeneratedSigmaAlgebraCollection ambient generator A → A ⊆ ambient
```
-/
theorem GeneratedSigmaAlgebraMembersAreSubsets
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A, GeneratedSigmaAlgebraCollection ambient generator A →
      A ⊆ ambient := by
  sorry

/--
**[Theorem — Generated Sigma Algebra Empty Is Member]** The empty set belongs
to the generated sigma-algebra.

Logical form:

```lean
GeneratedSigmaAlgebraCollection ambient generator (∅ : SetObject)
```
-/
theorem GeneratedSigmaAlgebraEmptyIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    GeneratedSigmaAlgebraCollection ambient generator (∅ : SetObject) := by
  sorry

/--
**[Theorem — Generated Sigma Algebra Union Is Member]** The generated
sigma-algebra is closed under binary union.

Logical form:

```lean
∀ A B,
  GeneratedSigmaAlgebraCollection ambient generator A →
  GeneratedSigmaAlgebraCollection ambient generator B →
  GeneratedSigmaAlgebraCollection ambient generator (A ∪ B)
```
-/
theorem GeneratedSigmaAlgebraUnionIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A B,
      GeneratedSigmaAlgebraCollection ambient generator A →
      GeneratedSigmaAlgebraCollection ambient generator B →
      GeneratedSigmaAlgebraCollection ambient generator (A ∪ B) := by
  sorry

/--
**[Theorem — Generated Sigma Algebra Intersection Is Member]** The generated
sigma-algebra is closed under binary intersection.

Logical form:

```lean
∀ A B,
  GeneratedSigmaAlgebraCollection ambient generator A →
  GeneratedSigmaAlgebraCollection ambient generator B →
  GeneratedSigmaAlgebraCollection ambient generator (A ∩ B)
```
-/
theorem GeneratedSigmaAlgebraIntersectionIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A B,
      GeneratedSigmaAlgebraCollection ambient generator A →
      GeneratedSigmaAlgebraCollection ambient generator B →
      GeneratedSigmaAlgebraCollection ambient generator (A ∩ B) := by
  sorry

/--
**[Theorem — Generated Sigma Algebra Difference Is Member]** The generated
sigma-algebra is closed under relative difference.

Logical form:

```lean
∀ A B,
  GeneratedSigmaAlgebraCollection ambient generator A →
  GeneratedSigmaAlgebraCollection ambient generator B →
  GeneratedSigmaAlgebraCollection ambient generator (A \ B)
```
-/
theorem GeneratedSigmaAlgebraDifferenceIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A B,
      GeneratedSigmaAlgebraCollection ambient generator A →
      GeneratedSigmaAlgebraCollection ambient generator B →
      GeneratedSigmaAlgebraCollection ambient generator (A \ B) := by
  sorry

/--
**[Theorem — Generated Sigma Algebra Symmetric Difference Is Member]** The
generated sigma-algebra is closed under symmetric difference.

Logical form:

```lean
∀ A B,
  GeneratedSigmaAlgebraCollection ambient generator A →
  GeneratedSigmaAlgebraCollection ambient generator B →
  GeneratedSigmaAlgebraCollection ambient generator (A ∆ B)
```
-/
theorem GeneratedSigmaAlgebraSymmetricDifferenceIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A B,
      GeneratedSigmaAlgebraCollection ambient generator A →
      GeneratedSigmaAlgebraCollection ambient generator B →
      GeneratedSigmaAlgebraCollection ambient generator (A ∆ B) := by
  sorry

/--
**[Theorem — Generated Sigma Algebra Ambient Is Member]** The ambient set
belongs to the generated sigma-algebra.

Logical form:

```lean
GeneratedSigmaAlgebraCollection ambient generator ambient
```
-/
theorem GeneratedSigmaAlgebraAmbientIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    GeneratedSigmaAlgebraCollection ambient generator ambient := by
  sorry

/--
**[Theorem — Generated Sigma Algebra Countable Union Is Member]** The
generated sigma-algebra is closed under countable unions.

Logical form:

```lean
∀ family : Nat → SetObject,
  (∀ index, GeneratedSigmaAlgebraCollection ambient generator
    (family index)) →
    GeneratedSigmaAlgebraCollection ambient generator
      (HasCountableUnion.countableUnion family)
```
-/
theorem GeneratedSigmaAlgebraCountableUnionIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ family : Nat → SetObject,
      (∀ index, GeneratedSigmaAlgebraCollection ambient generator
        (family index)) →
        GeneratedSigmaAlgebraCollection ambient generator
          (HasCountableUnion.countableUnion family) := by
  sorry

/-- The sigma-algebra generated by `generator` on `ambient`: the smallest
sigma-algebra admitting every generator. The closure fields are the
standard intersection argument, pending proof.

Logical form:

```lean
∀ A : SetObject,
  (GeneratedSigmaAlgebra ambient generator).IsMember A ↔
    GeneratedSigmaAlgebraCollection ambient generator A
```
-/
def GeneratedSigmaAlgebra
    (ambient : SetObject) (generator : SetObject → Prop) :
    SigmaAlgebraOfSets ambient where
  IsMember := GeneratedSigmaAlgebraCollection ambient generator
  MembersAreSubsets := GeneratedSigmaAlgebraMembersAreSubsets ambient generator
  EmptyIsMember := GeneratedSigmaAlgebraEmptyIsMember ambient generator
  UnionIsMember := GeneratedSigmaAlgebraUnionIsMember ambient generator
  IntersectionIsMember :=
    GeneratedSigmaAlgebraIntersectionIsMember ambient generator
  DifferenceIsMember := GeneratedSigmaAlgebraDifferenceIsMember ambient generator
  SymmetricDifferenceIsMember :=
    GeneratedSigmaAlgebraSymmetricDifferenceIsMember ambient generator
  AmbientIsMember := GeneratedSigmaAlgebraAmbientIsMember ambient generator
  CountableUnionIsMember :=
    GeneratedSigmaAlgebraCountableUnionIsMember ambient generator

/-- Every subset-of-ambient generator is a member of the sigma-algebra it
generates.

Logical form:

```lean
theorem GeneratedSigmaAlgebraContainsGenerator
    (ambient : SetObject) (generator : SetObject → Prop)
    (G : SetObject) (GIsGenerator : generator G) :
    (GeneratedSigmaAlgebra ambient generator).IsMember G
```
-/
theorem GeneratedSigmaAlgebraContainsGenerator
    (ambient : SetObject) (generator : SetObject → Prop)
    (G : SetObject) (GIsGenerator : generator G) :
    (GeneratedSigmaAlgebra ambient generator).IsMember G := by
  sorry

/-- Minimality: any sigma-algebra admitting the generators contains the
generated sigma-algebra. (Immediate from the definition -- the generated
collection is the intersection.)

Logical form:

```lean
theorem GeneratedSigmaAlgebraMinimal
    (ambient : SetObject) (generator : SetObject → Prop)
    (sigma : SigmaAlgebraOfSets ambient)
    (sigmaAdmitsGenerators : ∀ G, generator G → sigma.IsMember G) :
    ∀ A, (GeneratedSigmaAlgebra ambient generator).IsMember A →
      sigma.IsMember A
```
-/
theorem GeneratedSigmaAlgebraMinimal
    (ambient : SetObject) (generator : SetObject → Prop)
    (sigma : SigmaAlgebraOfSets ambient)
    (sigmaAdmitsGenerators : ∀ G, generator G → sigma.IsMember G) :
    ∀ A, (GeneratedSigmaAlgebra ambient generator).IsMember A →
      sigma.IsMember A := by
  sorry

/-- The Borel sigma-algebra on `ambient` determined by a family of open
sets: the sigma-algebra generated by the opens.

Logical form:

```lean
def BorelSigmaAlgebra
    (ambient : SetObject) (opens : SetObject → Prop) :
    SigmaAlgebraOfSets ambient :=
  GeneratedSigmaAlgebra ambient opens
```
-/
def BorelSigmaAlgebra
    (ambient : SetObject) (opens : SetObject → Prop) :
    SigmaAlgebraOfSets ambient :=
  GeneratedSigmaAlgebra ambient opens

end LRA.Set.Algebra
