import LRA.AlgebraicStructures.CompleteOrderedField.Interface.Definitions.Signature

namespace LRA.AlgebraicStructures.CompleteOrderedField.Interface.ModelTheory

end LRA.AlgebraicStructures.CompleteOrderedField.Interface.ModelTheory
