import LRA.AlgebraicStructures.CompleteOrderedField.Interface.Signature.Definition

namespace LRA.AlgebraicStructures.CompleteOrderedField.Interface.ModelTheory

end LRA.AlgebraicStructures.CompleteOrderedField.Interface.ModelTheory
