import LRA.Operation.Laws.Closure
import LRA.Operation.Laws.Associative
import LRA.Operation.Laws.Identity
import LRA.Operation.Laws.Inverse
import LRA.Operation.Laws.Commutative
import LRA.Operation.Laws.Absorbing
import LRA.Operation.Laws.Cancellation
import LRA.Operation.Laws.Idempotent
import LRA.Operation.Laws.Absorption
import LRA.Operation.Laws.Distributive
import LRA.Operation.Laws.Nilpotent
import LRA.Operation.Laws.QuotientCompatible
