import LRA.NumberSystems.ZeroBasedNaturals.Interface.Signature.Definition
import LRA.NumberSystems.ZeroBasedNaturals.Interface.ModelTheory.Model
import LRA.NumberSystems.ZeroBasedNaturals.Interface.UniversalAlgebra
