import LRA.NumberSystems.Integers.Constructions.Polish.TwoSidedSuccessor.Carrier
import LRA.NumberSystems.Integers.Constructions.Polish.TwoSidedSuccessor.Equivalence
import LRA.NumberSystems.Integers.Constructions.Polish.TwoSidedSuccessor.WellFoundedness
import LRA.NumberSystems.Integers.Constructions.Polish.TwoSidedSuccessor.Operations
import LRA.NumberSystems.Integers.Constructions.Polish.TwoSidedSuccessor.WellDefinedness
import LRA.NumberSystems.Integers.Constructions.Polish.TwoSidedSuccessor.Laws
import LRA.NumberSystems.Integers.Constructions.Polish.TwoSidedSuccessor.Behavior
import LRA.NumberSystems.Integers.Constructions.Polish.TwoSidedSuccessor.Instances
