-- LRA/VolumeII/PeanoSystems/PeanoAxioms.lean
--
-- The Peano Axioms — foundational primitives for Volume II.
-- No Mathlib. No imports.

namespace Peano

-- ============================================================
-- Primitive notions
-- ============================================================

/--
**[Axiom — N : Type]**

The carrier set of the canonical Peano system.
Its elements are the positive integers.

*Sources:* Landau, *Foundations of Analysis*, §1 Axiom 1
*Notes cross-ref:* §1.1 ax:peano-system-existence
-/
axiom N : Type

/--
**[Axiom — one : N]**

The distinguished initial element of the canonical Peano system.

*Sources:* Landau, *Foundations of Analysis*, §1 Axiom 1
*Notes cross-ref:* §1.1 ax:peano-system-existence
-/
axiom one : N

/--
**[Axiom — successor : N → N]**

The successor function.

*Sources:* Landau, *Foundations of Analysis*, §1 Axiom 2
*Notes cross-ref:* §1.1 def:peano-system
-/
axiom successor : N → N

-- ============================================================
-- Peano axioms
-- ============================================================

/--
**[Axiom — One Is Not a Successor]**

`successor x ≠ one` for every `x : N`.

*Sources:* Landau §1 Axiom 3; Feferman A3; Mendelson P3
*Notes cross-ref:* §1.1 ax:peano-one-not-successor
-/
axiom ax_one_not_successor :
  ∀ x : N, successor x ≠ one

/--
**[Axiom — Successor Is Injective]**

`successor x = successor y → x = y` for all `x y : N`.

*Sources:* Landau §1 Axiom 4; Feferman A4; Mendelson P4
*Notes cross-ref:* §1.1 ax:peano-successor-injective
-/
axiom ax_successor_injective :
  ∀ x y : N, successor x = successor y → x = y

/--
**[Axiom — Induction]**

If a property holds at `one` and is preserved by `successor`,
then it holds for every element of `N`.

*Sources:* Landau §1 Axiom 5; Feferman A5; Mendelson P5
*Notes cross-ref:* §1.1 ax:peano-induction
-/
axiom ax_induction :
  ∀ (P : N → Prop),
    P one →
    (∀ x : N, P x → P (successor x)) →
    ∀ x : N, P x

/--
**[Theorem — Induction Principle]**

A named wrapper around `ax_induction`.

*Dependencies:* `ax_induction`
*Notes cross-ref:* §1.1 thm:peano-induction-principle
-/
@[recursor 4]
theorem N_Induction {P : N → Prop}
    (base : P one)
    (step : ∀ n : N, P n → P (successor n)) :
    ∀ x : N, P x :=
  ax_induction P base step

-- ============================================================
-- Recursion / iterator machine
-- ============================================================

/--
**[Axiom — Recursion Machine]**

For any type `T`, initial value `base : T`, and step rule
`step : T → T`, `ax_recursion base step` is the function
`N → T` generated by primitive recursion.

This is the Peano Iterator Theorem stated axiomatically.

*Sources:*
  Feferman, *The Number Systems*, §3.4 Theorem 3.4
  Mendelson, *Number Systems*, §2.2 Theorem 2.1
*Notes cross-ref:* §1.2 thm:peano-iterator
-/
axiom ax_recursion :
  ∀ {T : Type}, T → (T → T) → N → T

/--
**[Axiom — Recursion Base Clause]**

`ax_recursion base step one = base`.

*Dependencies:* `ax_recursion`, `one`
*Notes cross-ref:* §1.2 thm:iterator-base-clause
-/
axiom ax_recursion_one :
  ∀ {T : Type} (base : T) (step : T → T),
    ax_recursion base step one = base

/--
**[Axiom — Recursion Successor Clause]**

`ax_recursion base step (successor n) =
 step (ax_recursion base step n)`.

*Dependencies:* `ax_recursion`, `successor`
*Notes cross-ref:* §1.2 thm:iterator-successor-clause
-/
axiom ax_recursion_successor :
  ∀ {T : Type} (base : T) (step : T → T) (n : N),
    ax_recursion base step (successor n) =
      step (ax_recursion base step n)

-- ============================================================
-- Public recursion names
-- ============================================================

noncomputable abbrev N_rec : ∀ {T : Type}, T → (T → T) → N → T :=
  ax_recursion

theorem N_rec_one {T : Type} (base : T) (step : T → T) :
    N_rec base step one = base :=
  ax_recursion_one base step

theorem N_rec_succ {T : Type} (base : T) (step : T → T) (n : N) :
    N_rec base step (successor n) =
      step (N_rec base step n) :=
  ax_recursion_successor base step n

end Peano
