-- LRA/VolumeII/PeanoSystems/Recursion.lean
--
-- Recursion and iterator machinery for abstract Peano systems.
-- No Mathlib.

import LRA.VolumeII.PeanoSystems.Induction

namespace Peano

/--
**[Definition — Iterator Data]**

Iterator data for a Peano system consists of a target type,
an initial value, and a step rule on the target type.

*Dependencies:* `PeanoSystem`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#definition-iterator-data](../notes/section_1_2_main.md#definition-iterator-data)
-/
structure IteratorData (ps : PeanoSystem) where
  target : Type
  initial_value : target
  step_rule : target → target

/--
**[Definition — Iterator Function Clauses]**

A function satisfies the iterator clauses exactly when it sends
the distinguished element to the initial value and sends successors
according to the step rule.

*Dependencies:* `PeanoSystem`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#definition-iterator-function-clauses](../notes/section_1_2_main.md#definition-iterator-function-clauses)
-/
def satisfies_iterator_clauses
    (ps : PeanoSystem)
    (target : Type)
    (initial_value : target)
    (step_rule : target → target)
    (iterator_function : ps.carrier → target) : Prop :=
  iterator_function ps.one = initial_value ∧
    ∀ element : ps.carrier,
      iterator_function (ps.successor element) =
        step_rule (iterator_function element)

/--
**[Existence of an Iterator Function]**

For every target type, initial value, and step rule, there exists
an iterator function satisfying the iterator clauses.

This is the temporary architectural existence interface. It should
eventually be replaced by the constructed proof from the minimal
iterator relation.

*Dependencies:* `PeanoSystem`, `satisfies_iterator_clauses`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#existence-of-an-iterator-function](../notes/section_1_2_main.md#existence-of-an-iterator-function)
-/
axiom iterator_function_exists :
  ∀ (ps : PeanoSystem)
    (target : Type)
    (initial_value : target)
    (step_rule : target → target),
    ∃ iterator_function : ps.carrier → target,
      satisfies_iterator_clauses
        ps
        target
        initial_value
        step_rule
        iterator_function

/--
**[Uniqueness of Iterator Functions]**

Any two iterator functions satisfying the same iterator clauses
are pointwise equal.

This is the temporary architectural uniqueness interface. It should
eventually be replaced by the induction proof.

*Dependencies:* `PeanoSystem`, `induction_principle`,
`satisfies_iterator_clauses`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#uniqueness-of-iterator-functions](../notes/section_1_2_main.md#uniqueness-of-iterator-functions)
-/
axiom iterator_function_unique :
  ∀ (ps : PeanoSystem)
    (target : Type)
    (initial_value : target)
    (step_rule : target → target)
    (first_iterator second_iterator : ps.carrier → target),
    satisfies_iterator_clauses
      ps
      target
      initial_value
      step_rule
      first_iterator →
    satisfies_iterator_clauses
      ps
      target
      initial_value
      step_rule
      second_iterator →
    ∀ element : ps.carrier,
      first_iterator element = second_iterator element

/--
**[Definition — Iterator-Generated Function]**

The iterator-generated function determined by a target type,
an initial value, and a step rule.

*Dependencies:* `iterator_function_exists`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#definition-iterator-generated-function](../notes/section_1_2_main.md#definition-iterator-generated-function)
-/
noncomputable def iter
    (ps : PeanoSystem)
    (target : Type)
    (initial_value : target)
    (step_rule : target → target) :
    ps.carrier → target :=
  Classical.choose
    (iterator_function_exists
      ps
      target
      initial_value
      step_rule)

/--
**[Theorem — Iterator-Generated Function Satisfies the Iterator Clauses]**

The function generated by `iter` satisfies the base and successor
clauses for the given iterator data.

*Dependencies:* `iter`, `iterator_function_exists`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#theorem-iterator-generated-function-satisfies-the-iterator-clauses](../notes/section_1_2_main.md#theorem-iterator-generated-function-satisfies-the-iterator-clauses)
-/
theorem iter_satisfies_iterator_clauses
    (ps : PeanoSystem)
    (target : Type)
    (initial_value : target)
    (step_rule : target → target) :
    satisfies_iterator_clauses
      ps
      target
      initial_value
      step_rule
      (iter ps target initial_value step_rule) :=
  Classical.choose_spec
    (iterator_function_exists
      ps
      target
      initial_value
      step_rule)

/--
**[Theorem — Iterator Base Clause]**

The iterator-generated function sends the distinguished element
to the initial value.

*Dependencies:* `iter_satisfies_iterator_clauses`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#theorem-iterator-base-clause](../notes/section_1_2_main.md#theorem-iterator-base-clause)
-/
theorem iter_base
    (ps : PeanoSystem)
    (target : Type)
    (initial_value : target)
    (step_rule : target → target) :
    iter ps target initial_value step_rule ps.one = initial_value :=
  (iter_satisfies_iterator_clauses
    ps
    target
    initial_value
    step_rule).left

/--
**[Theorem — Iterator Successor Clause]**

The iterator-generated function sends successors according to
the step rule.

*Dependencies:* `iter_satisfies_iterator_clauses`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#theorem-iterator-successor-clause](../notes/section_1_2_main.md#theorem-iterator-successor-clause)
-/
theorem iter_step
    (ps : PeanoSystem)
    (target : Type)
    (initial_value : target)
    (step_rule : target → target)
    (element : ps.carrier) :
    iter ps target initial_value step_rule (ps.successor element) =
      step_rule (iter ps target initial_value step_rule element) :=
  (iter_satisfies_iterator_clauses
    ps
    target
    initial_value
    step_rule).right element

/--
**[Theorem — Peano Iterator Theorem]**

For every target type, initial value, and step rule, there exists
an iterator function satisfying the iterator clauses, and any other
such function is pointwise equal to it.

*Dependencies:* `iterator_function_exists`, `iterator_function_unique`

*Sources:*
  Feferman, *The Number Systems*, §3.4
  Mendelson, *Number Systems*, §2.2

*Notes cross-ref:* §1.2 [#theorem-peano-iterator-theorem](../notes/section_1_2_main.md#theorem-peano-iterator-theorem)
-/
theorem peano_iterator_theorem
    (ps : PeanoSystem)
    (target : Type)
    (initial_value : target)
    (step_rule : target → target) :
    ∃ iterator_function : ps.carrier → target,
      satisfies_iterator_clauses
        ps
        target
        initial_value
        step_rule
        iterator_function ∧
      ∀ other_iterator : ps.carrier → target,
        satisfies_iterator_clauses
          ps
          target
          initial_value
          step_rule
          other_iterator →
        ∀ element : ps.carrier,
          other_iterator element = iterator_function element := by
  refine
    ⟨iter ps target initial_value step_rule,
      iter_satisfies_iterator_clauses ps target initial_value step_rule,
      ?_⟩
  intro other_iterator other_iterator_satisfies_clauses element
  exact
    Eq.symm
      (iterator_function_unique
        ps
        target
        initial_value
        step_rule
        (iter ps target initial_value step_rule)
        other_iterator
        (iter_satisfies_iterator_clauses
          ps
          target
          initial_value
          step_rule)
        other_iterator_satisfies_clauses
        element)

end Peano
