import LRA.AlgebraicStructures.IntegralDomain.Interface.Signature.Definition

namespace LRA.AlgebraicStructures.IntegralDomain.Interface.ModelTheory

end LRA.AlgebraicStructures.IntegralDomain.Interface.ModelTheory
