import LRA.AlgebraicStructures.IntegralDomain.Interface.Definitions.Signature

namespace LRA.AlgebraicStructures.IntegralDomain.Interface.ModelTheory

end LRA.AlgebraicStructures.IntegralDomain.Interface.ModelTheory
