import LRA.AlgebraicStructures.OrderedSemiring.Interface.ModelTheory.Theory
import LRA.AlgebraicStructures.OrderedSemiring.Interface.ModelTheory.LStructure

namespace LRA.AlgebraicStructures.OrderedSemiring.Interface.ModelTheory

end LRA.AlgebraicStructures.OrderedSemiring.Interface.ModelTheory
