import LRA.AlgebraicStructures.OrderedSemiring.Interface.Definitions.Signature

namespace LRA.AlgebraicStructures.OrderedSemiring.Interface.ModelTheory

end LRA.AlgebraicStructures.OrderedSemiring.Interface.ModelTheory
