import LRA.VolumeI.Logic.Semantics.Satisfaction
import LRA.VolumeI.Set.ZFC.Model.Model
import LRA.VolumeI.Set.ZFC.Syntax.Formula
import LRA.VolumeI.Set.ZFC.Theory.Axioms
import LRA.VolumeI.Set.ZFC.Theory.Schemas

namespace LRA.VolumeI.Set.ZFC

open LRA.VolumeI.Logic

/-!
Satisfaction of ZFC formulas.

The generic first-order layer already supplies the satisfaction relation.
This module gives it a ZFC-facing name specialized to the ZFC signature
and variable type, and packages the model-facing predicates that say a
ZFC model satisfies the ZFC axioms.
-/

/-- Satisfaction of a ZFC formula in a ZFC model under a variable
assignment. -/
def satisfiesZFCFormula
    (M : ZFCModel)
    (assignment : ZFCVariable -> M.Domain)
    (φ : ZFCFormula) : Prop :=
  FirstOrder.Satisfies M assignment φ

/-!
Model-facing ZFC axiom predicates.

The named axioms are intended as closed formulas, but the current
first-order layer does not yet package closed formulas/sentences or prove
assignment-independence for formulas with no free variables. Until that
layer exists, these predicates quantify over assignments explicitly.

Note on equality: because `=` is a primitive logical symbol interpreted by
`Satisfies` as *actual* equality on the model's domain, the congruence
properties of equality (reflexivity and the substitution schema
`x = y → (φ(x) ↔ φ(y))`) hold automatically in every model and need no
axioms here. That convenience is purely semantic: the eventual proof
theory (a Hilbert or sequent system for this logic) *will* need explicit
equality and congruence axioms, since it cannot appeal to a Tarskian
interpretation. Nothing to add at the model layer; this is a marker for
that later work.
-/

/-- A ZFC model satisfies the currently formalized non-schema ZFC axioms:
extensionality, empty set, pairing, union, power set, foundation, and
infinity. -/
def SatisfiesZFCBasicAxioms (M : ZFCModel) : Prop :=
  ∀ assignment : ZFCVariable -> M.Domain,
    satisfiesZFCFormula M assignment extensionalityAxiom ∧
    satisfiesZFCFormula M assignment emptySetAxiom ∧
    satisfiesZFCFormula M assignment pairingAxiom ∧
    satisfiesZFCFormula M assignment unionAxiom ∧
    satisfiesZFCFormula M assignment powerSetAxiom ∧
    satisfiesZFCFormula M assignment foundationAxiom ∧
    satisfiesZFCFormula M assignment infinityAxiom

/-- A ZFC model satisfies every instance of the Separation schema
generated by `separationAxiomFor`. -/
def SatisfiesSeparationSchema (M : ZFCModel) : Prop :=
  ∀ (elementVariable : ZFCVariable)
    (predicate : ZFCFormula)
    (assignment : ZFCVariable -> M.Domain),
      satisfiesZFCFormula M assignment (separationAxiomFor elementVariable predicate)

/-- A ZFC model satisfies the currently formalized axioms except
Replacement: the named non-schema axioms plus every Separation instance. -/
def SatisfiesZFCAxiomsWithoutReplacement (M : ZFCModel) : Prop :=
  SatisfiesZFCBasicAxioms M ∧ SatisfiesSeparationSchema M

/-- A ZFC model satisfies every instance of the Replacement schema
generated by `replacementAxiomFor`. -/
def SatisfiesReplacementSchema (M : ZFCModel) : Prop :=
  ∀ (inputVariable outputVariable : ZFCVariable)
    (predicate : ZFCFormula)
    (assignment : ZFCVariable -> M.Domain),
      satisfiesZFCFormula M assignment
        (replacementAxiomFor inputVariable outputVariable predicate)

/-- A ZFC model satisfies all currently formalized ZFC axioms *except
Choice* (whose precise first-order statement is deliberately deferred):
the named non-schema axioms plus every Separation and Replacement
instance. -/
def SatisfiesZFCAxiomsWithoutChoice (M : ZFCModel) : Prop :=
  SatisfiesZFCBasicAxioms M ∧
    SatisfiesSeparationSchema M ∧
    SatisfiesReplacementSchema M

end LRA.VolumeI.Set.ZFC
