import LRA.AlgebraicStructures.Magma.Examples.RockPaperScissors
import LRA.AlgebraicStructures.Magma.Examples.IntegersUnderSubtraction
import LRA.AlgebraicStructures.Magma.Examples.NonzeroRealsUnderDivision
import LRA.AlgebraicStructures.Magma.Examples.NonemptyZFCSetsUnderUnion
import LRA.AlgebraicStructures.Magma.Examples.IdentityNotRequired
