import LRA.EuclideanSpace.Interface
import LRA.EuclideanSpace.Model
import LRA.EuclideanSpace.Tarski
import LRA.EuclideanSpace.MathlibPoint
import LRA.EuclideanSpace.RealLine

   
                                                                    
               

        

                                                                   
                                                                        
                                                                     
                                                              
                                                               
                                                                       
                                                                    
               

                                      

                                                                 
                                                               
                                                               
                                                                     
                                                             
                        
                                                                      
                                                                   
                              

                        

                                                                
                                                                        
                                                               
                                                      
                                                                  
                                                        

                                                                  
                                                                        
                                                                      
                                        

                                                                       
                                                                     
                                                                        
                                              
                                       

            

                                                                    
                                                                 
                                                              

                                                                     
                                                                
                                                                       
                                                                  
                                                               
                                                  
                                                                
                                                                    
                                                                  
                                                                
                                                                      
                                                                
                                                                   
                                                                        
                                 
                                                               
                                                                        
                                                               
                                                                     
                                                                       
                                                                   
                                                                 
  
