import LRA.AlgebraicStructures.AdditiveSemigroup.Examples.PositiveNaturalsUnderAddition
import LRA.AlgebraicStructures.AdditiveSemigroup.Examples.EvenIntegersUnderAddition
import LRA.AlgebraicStructures.AdditiveSemigroup.Examples.PositiveEvenNaturalsUnderAddition
