import LRA.AlgebraicStructures.AdditiveCommutativeSemigroup.All
import LRA.AlgebraicStructures.AdditiveCommutativeSemigroup.Examples
import LRA.AlgebraicStructures.AdditiveCommutativeSemigroup.FailureModes
