import LRA.AlgebraicStructures.AdditiveCommutativeSemigroup.Examples.PositiveNaturalsUnderAddition
import LRA.AlgebraicStructures.AdditiveCommutativeSemigroup.Examples.PositiveEvenNaturalsUnderAddition
import LRA.AlgebraicStructures.AdditiveCommutativeSemigroup.Examples.OpenIntervalUnderAddition
