import LRA.NumberSystems.PeanoSystem.Definition
import LRA.Logic.Model.Model

/-!
First-order signature and model data for the Peano-system natural-number
language.
-/

namespace LRA.NumberSystems.NaturalNumbers

universe u v

variable {Element : Type u} {SetObject : Type v}
variable [Membership Element SetObject]


/--
`NFunctionSymbol` is generated by the displayed constructors for n function symbol.

Logical form:

```lean
inductive NFunctionSymbol where
  | successor
```
-/
inductive NFunctionSymbol where
  | successor

/--
`NRelationSymbol` defines the displayed object for n relation symbol.

Logical form:

```lean
def NRelationSymbol : Type := Empty
```
-/
def NRelationSymbol : Type := Empty

/--
`NConstantSymbol` is generated by the displayed constructors for n constant symbol.

Logical form:

```lean
inductive NConstantSymbol where
  | one
```
-/
inductive NConstantSymbol where
  | one

/--
`NFunctions` defines the displayed object for n functions.

Logical form:

```lean
def NFunctions : LRA.Logic.ArityIndexedSymbols where
  Symbol := NFunctionSymbol
  arity
    | .successor => 1
```
-/
def NFunctions : LRA.Logic.ArityIndexedSymbols where
  Symbol := NFunctionSymbol
  arity
    | .successor => 1

/--
`NRelations` defines the displayed object for n relations.

Logical form:

```lean
def NRelations : LRA.Logic.ArityIndexedSymbols where
  Symbol := NRelationSymbol
  arity := Empty.elim
```
-/
def NRelations : LRA.Logic.ArityIndexedSymbols where
  Symbol := NRelationSymbol
  arity := Empty.elim

/--
`NSignature` defines the displayed object for n signature.

Logical form:

```lean
def NSignature : LRA.Logic.Signature where
  Functions := NFunctions
  Relations := NRelations
  Constants := NConstantSymbol
```
-/
def NSignature : LRA.Logic.Signature where
  Functions := NFunctions
  Relations := NRelations
  Constants := NConstantSymbol

/--
`NModel` packages the data and laws for n model.

Logical form:

```lean
structure NModel (Element : Type u) (SetObject : Type v)
    [Membership Element SetObject]
    extends LRA.NumberSystems.PeanoSystem.PeanoSystem Element SetObject
```
-/
structure NModel (Element : Type u) (SetObject : Type v)
    [Membership Element SetObject]
    extends LRA.NumberSystems.PeanoSystem.PeanoSystem Element SetObject

/--
`NModel.toFirstOrderModel` defines the displayed object for to first order model.

Logical form:

```lean
def NModel.toFirstOrderModel
    (model : NModel Element SetObject) :
    LRA.Logic.FirstOrder.Model NSignature where
  Domain := Element
  domainNonempty := ⟨model.one⟩
  interpretFunction
    | .successor, args => model.successor (args ⟨0, by decide⟩)
  interpretRelation := fun relation_symbol => nomatch relation_symbol
  interpretConstant
    | .one => model.one
```
-/
def NModel.toFirstOrderModel
    (model : NModel Element SetObject) :
    LRA.Logic.FirstOrder.Model NSignature where
  Domain := Element
  domainNonempty := ⟨model.one⟩
  interpretFunction
    | .successor, args => model.successor (args ⟨0, by decide⟩)
  interpretRelation := fun relation_symbol => nomatch relation_symbol
  interpretConstant
    | .one => model.one

end LRA.NumberSystems.NaturalNumbers
