-- LRA/VolumeII/Integers/Polish/DiscreteIntegerStructure.lean
-- Abstract two-sided successor/predecessor axioms for integer structures.

namespace LRA
namespace VolumeII
namespace Integers
namespace Polish

/-!
Volume II label: integers-polish-discrete-integer-structure
Lean module: LRA.VolumeII.Integers.Polish.DiscreteIntegerStructure
Verification status: experimental statement/proof work

This module formalizes the abstract `(Z1)`--`(Z3)` integer-structure axioms:

* successor and predecessor are mutual inverses,
* positive successor iterates of zero are aperiodic,
* two-sided induction holds.

The intended theorem is categoricity: every such structure is represented by
the built-in `Int` through the unique walk generated by `succ` and `pred`.
-/

def iterate {α : Type u} (f : α → α) : Nat → α → α
  | 0, x => x
  | n + 1, x => f (iterate f n x)

theorem iterate_succ' {α : Type u} (f : α → α) (n : Nat) (x : α) :
    iterate f (n + 1) x = f (iterate f n x) := rfl

theorem iterate_comm {α : Type u} (f : α → α) (n : Nat) (x : α) :
    f (iterate f n x) = iterate f n (f x) := by
  induction n with
  | zero => rfl
  | succ k ih =>
      show f (f (iterate f k x)) = iterate f (k + 1) (f x)
      rw [ih]
      rfl

theorem iterate_succ_apply {α : Type u} (f : α → α) (n : Nat) (x : α) :
    iterate f (n + 1) x = iterate f n (f x) :=
  iterate_comm f n x

theorem iterate_add {α : Type u} (f : α → α) (m n : Nat) (x : α) :
    iterate f (m + n) x = iterate f m (iterate f n x) := by
  induction n with
  | zero => rfl
  | succ k ih =>
      show f (iterate f (m + k) x) = iterate f m (f (iterate f k x))
      rw [ih]
      exact iterate_comm f m (iterate f k x)

def Injective {α β : Type _} (f : α → β) : Prop :=
  ∀ ⦃a b⦄, f a = f b → a = b

def Surjective {α β : Type _} (f : α → β) : Prop :=
  ∀ b, ∃ a, f a = b

def Bijective {α β : Type _} (f : α → β) : Prop :=
  Injective f ∧ Surjective f

structure IntegerStructure where
  carrier : Type u
  zero : carrier
  succ : carrier → carrier
  pred : carrier → carrier
  pred_succ : ∀ x, pred (succ x) = x
  succ_pred : ∀ x, succ (pred x) = x
  aperiodic : ∀ n : Nat, 0 < n → iterate succ n zero ≠ zero
  induction :
    ∀ (A : carrier → Prop),
      A zero →
      (∀ x, A x → A (succ x)) →
      (∀ x, A x → A (pred x)) →
      ∀ x, A x

namespace IntegerStructure

variable (S : IntegerStructure)

def rep : Int → S.carrier
  | Int.ofNat n => iterate S.succ n S.zero
  | Int.negSucc n => iterate S.pred (n + 1) S.zero

@[simp] theorem rep_zero : S.rep 0 = S.zero := rfl

theorem pred_iterate_succ_iterate (n : Nat) (x : S.carrier) :
    iterate S.pred n (iterate S.succ n x) = x := by
  induction n with
  | zero => rfl
  | succ k ih =>
      rw [
        iterate_succ' S.succ k x,
        iterate_succ_apply S.pred k (S.succ (iterate S.succ k x)),
        S.pred_succ
      ]
      exact ih

theorem succ_iterate_pred_iterate (n : Nat) (x : S.carrier) :
    iterate S.succ n (iterate S.pred n x) = x := by
  induction n with
  | zero => rfl
  | succ k ih =>
      rw [
        iterate_succ' S.pred k x,
        iterate_succ_apply S.succ k (S.pred (iterate S.pred k x)),
        S.succ_pred
      ]
      exact ih

theorem aperiodic_pred (n : Nat) (h : 0 < n) :
    iterate S.pred n S.zero ≠ S.zero := by
  intro heq
  apply S.aperiodic n h
  have h2 := congrArg (iterate S.succ n) heq
  rw [S.succ_iterate_pred_iterate] at h2
  exact h2.symm

theorem iterate_succ_injective (n : Nat) : Injective (iterate S.succ n) := by
  intro x y hxy
  have h := congrArg (iterate S.pred n) hxy
  rw [S.pred_iterate_succ_iterate, S.pred_iterate_succ_iterate] at h
  exact h

theorem iterate_pred_injective (n : Nat) : Injective (iterate S.pred n) := by
  intro x y hxy
  have h := congrArg (iterate S.succ n) hxy
  rw [S.succ_iterate_pred_iterate, S.succ_iterate_pred_iterate] at h
  exact h

theorem no_forward_collision
    (m n : Nat)
    (h : iterate S.succ m S.zero = iterate S.succ n S.zero) :
    m = n := by
  rcases Nat.le_total m n with hmn | hmn
  · obtain ⟨k, rfl⟩ := Nat.le.dest hmn
    have h1 :
        iterate S.succ m S.zero =
          iterate S.succ m (iterate S.succ k S.zero) := by
      rw [← iterate_add]
      exact h
    have hz : iterate S.succ k S.zero = S.zero :=
      (S.iterate_succ_injective m) h1.symm
    rcases Nat.eq_zero_or_pos k with hk | hk
    · omega
    · exact absurd hz (S.aperiodic k hk)
  · obtain ⟨k, rfl⟩ := Nat.le.dest hmn
    have h1 :
        iterate S.succ n S.zero =
          iterate S.succ n (iterate S.succ k S.zero) := by
      rw [← iterate_add]
      exact h.symm
    have hz : iterate S.succ k S.zero = S.zero :=
      (S.iterate_succ_injective n) h1.symm
    rcases Nat.eq_zero_or_pos k with hk | hk
    · omega
    · exact absurd hz (S.aperiodic k hk)

theorem no_backward_collision
    (m n : Nat)
    (h : iterate S.pred m S.zero = iterate S.pred n S.zero) :
    m = n := by
  rcases Nat.le_total m n with hmn | hmn
  · obtain ⟨k, rfl⟩ := Nat.le.dest hmn
    have h1 :
        iterate S.pred m S.zero =
          iterate S.pred m (iterate S.pred k S.zero) := by
      rw [← iterate_add]
      exact h
    have hz : iterate S.pred k S.zero = S.zero :=
      (S.iterate_pred_injective m) h1.symm
    rcases Nat.eq_zero_or_pos k with hk | hk
    · omega
    · exact absurd hz (S.aperiodic_pred k hk)
  · obtain ⟨k, rfl⟩ := Nat.le.dest hmn
    have h1 :
        iterate S.pred n S.zero =
          iterate S.pred n (iterate S.pred k S.zero) := by
      rw [← iterate_add]
      exact h.symm
    have hz : iterate S.pred k S.zero = S.zero :=
      (S.iterate_pred_injective n) h1.symm
    rcases Nat.eq_zero_or_pos k with hk | hk
    · omega
    · exact absurd hz (S.aperiodic_pred k hk)

theorem no_mixed_collision
    (m n : Nat)
    (h : iterate S.succ m S.zero = iterate S.pred (n + 1) S.zero) :
    False := by
  have h1 := congrArg (iterate S.succ (n + 1)) h
  rw [S.succ_iterate_pred_iterate] at h1
  rw [← iterate_add] at h1
  exact absurd h1 (S.aperiodic (n + 1 + m) (by omega))

theorem rep_injective : Injective S.rep := by
  intro a b hab
  match a, b with
  | Int.ofNat m, Int.ofNat n =>
      have heq : m = n := S.no_forward_collision m n hab
      subst heq
      rfl
  | Int.negSucc m, Int.negSucc n =>
      have hab' :
          iterate S.pred (m + 1) S.zero =
            iterate S.pred (n + 1) S.zero := hab
      have heq : m + 1 = n + 1 :=
        S.no_backward_collision (m + 1) (n + 1) hab'
      have hmn : m = n := by omega
      subst hmn
      rfl
  | Int.ofNat m, Int.negSucc n =>
      exact absurd hab (S.no_mixed_collision m n)
  | Int.negSucc m, Int.ofNat n =>
      exact absurd hab.symm (S.no_mixed_collision n m)

theorem rep_succ (n : Int) : S.rep (n + 1) = S.succ (S.rep n) := by
  match n with
  | Int.ofNat k => rfl
  | Int.negSucc 0 =>
      show S.rep 0 = S.succ (S.rep (Int.negSucc 0))
      show S.zero = S.succ (iterate S.pred 1 S.zero)
      show S.zero = S.succ (S.pred S.zero)
      rw [S.succ_pred]
  | Int.negSucc (k + 1) =>
      have hcast : Int.negSucc (k + 1) + 1 = Int.negSucc k := by omega
      rw [hcast]
      show
        iterate S.pred (k + 1) S.zero =
          S.succ (iterate S.pred (k + 2) S.zero)
      have step :
          iterate S.pred (k + 2) S.zero =
            S.pred (iterate S.pred (k + 1) S.zero) := rfl
      rw [step, S.succ_pred]

theorem rep_pred (n : Int) : S.rep (n - 1) = S.pred (S.rep n) := by
  have h := S.rep_succ (n - 1)
  have hn : n - 1 + 1 = n := by omega
  rw [hn] at h
  have h2 := congrArg S.pred h
  rw [S.pred_succ] at h2
  exact h2.symm

theorem rep_surjective : Surjective S.rep := by
  intro x
  apply S.induction (fun x => ∃ n : Int, S.rep n = x)
  · exact ⟨0, S.rep_zero⟩
  · rintro y ⟨n, rfl⟩
    exact ⟨n + 1, S.rep_succ n⟩
  · rintro y ⟨n, rfl⟩
    exact ⟨n - 1, S.rep_pred n⟩

theorem rep_bijective : Bijective S.rep :=
  ⟨S.rep_injective, S.rep_surjective⟩

theorem categoricity :
    Bijective S.rep ∧
      S.rep 0 = S.zero ∧
      ∀ n : Int, S.rep (n + 1) = S.succ (S.rep n) :=
  ⟨S.rep_bijective, S.rep_zero, S.rep_succ⟩

end IntegerStructure
end Polish
end Integers
end VolumeII
end LRA
