-- LRA/VolumeII/NaturalNumbers/PeanoN.lean
--
-- The canonical concrete Peano system.
--
-- This file defines PN, the inductive witness for the Peano axioms.
-- PN is built from first principles as a two-constructor inductive
-- type: one distinguished element and a successor operation.
--
-- This is the internal concrete type used throughout NaturalNumbers.
-- See StandardN.lean for the bridge to Lean's Nat.
--
-- Sources:
--   Landau,   Foundations of Analysis, §1
--   Feferman, The Number Systems, §3.1–3.2
--   Dedekind, Essays on the Theory of Numbers, §6
--
-- Running table of contents:
--
--   Inductive | PN                      | the concrete Peano type
--   Instance  | PN_is_peano_system      | PN satisfies PeanoSystem
--   Theorem   | PN_peano_system_exists  | witness for existence axiom
--   Theorem   | pn_iso_any_peano_system | unique iso to any PeanoSystem

import LRA.VolumeII.PeanoSystems.Recursion
import LRA.VolumeII.PeanoSystems.BasicTheorems

namespace LRA
namespace VolumeII
namespace NaturalNumbers

open LRA.VolumeII.PeanoSystems


-- ============================================================
-- The PN inductive type
-- ============================================================

/--
**[Definition — PN : The Canonical Peano Type]**

`PN` is the canonical concrete inductive witness for the Peano axioms.
Two constructors: a distinguished first element `one` and a successor
operation `succ`. All other elements are generated by iterating `succ`
from `one`. The name PN stands for Peano Natural, analogous to ℕ.

*Dependencies:* none

*Sources:*
  Landau,   *Foundations of Analysis*, §1
  Feferman, *The Number Systems*, §3.1
  Dedekind, *Essays on the Theory of Numbers*, §6

*Notes cross-ref:* §1.1 [def:peano-system](../notes/section_1_1_main.md)
-/
inductive PN : Type where
  | one  : PN
  | succ : PN → PN

-- ============================================================
-- PN is a Peano system
-- ============================================================

/--
**[Instance — PN Is a Peano System]**

The inductive type `PN` with constructor `one` and operation `succ`
satisfies all five Peano axioms.

*Dependencies:* `PN`, `PeanoSystem`

*Sources:*
  Landau,   *Foundations of Analysis*, §1
  Feferman, *The Number Systems*, §3.2

*Notes cross-ref:* §1.1 [ax:peano-system-existence](../notes/section_1_1_main.md)
-/
def PN_is_peano_system : PeanoSystem.{0} where
  carrier             := PN
  one                 := PN.one
  successor           := PN.succ
  one_not_successor   := by
    intro element
    exact PN.noConfusion
  successor_injective := by
    intro first_element second_element equality_of_successors
    exact PN.succ.inj equality_of_successors
  induction           := by
    intro predicate base_case successor_step element
    induction element with
    | one       => exact base_case
    | succ n induction_hypothesis =>
        exact successor_step n induction_hypothesis

-- ============================================================
-- PN witnesses the existence of a Peano system
-- ============================================================

/--
**[Theorem — A Peano System Exists]**

`PN` is a concrete witness for the existence of a Peano system in the base Lean
universe, discharging the concrete existence obligation used by Volume II.

*Dependencies:* `PN_is_peano_system`

*Sources:* Feferman, *The Number Systems*, §3.2 Axiom 3.2

*Notes cross-ref:* §1.1 [ax:peano-system-existence](../notes/section_1_1_main.md)
-/
theorem PN_peano_system_exists : Nonempty (PeanoSystem.{0}) :=
  ⟨PN_is_peano_system⟩

-- ============================================================
-- PN is initial: unique morphism into any base-universe Peano system
-- ============================================================

/--
**[Theorem — PN Is Initial Among Peano Systems]**

For any base-universe Peano system `peano_system`, there exists a unique
structure-preserving map from `PN` to its carrier. This is the Peano Iterator
Theorem applied with the target equal to the carrier of `peano_system`.

*Dependencies:* `PN_is_peano_system`, `iter`, `iter_base`, `iter_step`,
`iterator_function_unique`

*Sources:*
  Feferman, *The Number Systems*, §3.5 Theorem 3.5
  Simpson,  *Peano Systems*, Theorem 4

*Notes cross-ref:* §1.2
[thm:uniqueness-of-peano-systems-up-to-isomorphism](../notes/section_1_2_main.md)
-/
theorem pn_iso_any_peano_system
    (peano_system : PeanoSystem.{0}) :
    ∃ structure_preserving_map : PN → peano_system.carrier,
      structure_preserving_map PN.one = peano_system.one ∧
      (∀ natural_value : PN,
        structure_preserving_map (PN.succ natural_value) =
          peano_system.successor
            (structure_preserving_map natural_value)) ∧
      (∀ other_map : PN → peano_system.carrier,
        other_map PN.one = peano_system.one →
        (∀ natural_value : PN,
          other_map (PN.succ natural_value) =
            peano_system.successor (other_map natural_value)) →
        ∀ natural_value : PN,
          other_map natural_value =
            structure_preserving_map natural_value) := by
  let structure_preserving_map : PN → peano_system.carrier :=
    iter
      PN_is_peano_system
      peano_system.carrier
      peano_system.one
      peano_system.successor
  refine ⟨structure_preserving_map, ?_, ?_, ?_⟩
  · exact
      iter_base
        PN_is_peano_system
        peano_system.carrier
        peano_system.one
        peano_system.successor
  · intro natural_value
    exact
      iter_step
        PN_is_peano_system
        peano_system.carrier
        peano_system.one
        peano_system.successor
        natural_value
  · intro other_map other_map_base other_map_step
    exact
      iterator_function_unique
        PN_is_peano_system
        peano_system.carrier
        peano_system.one
        peano_system.successor
        other_map
        structure_preserving_map
        ⟨other_map_base, other_map_step⟩
        ⟨iter_base
            PN_is_peano_system
            peano_system.carrier
            peano_system.one
            peano_system.successor,
          iter_step
            PN_is_peano_system
            peano_system.carrier
            peano_system.one
            peano_system.successor⟩

end NaturalNumbers
end VolumeII
end LRA
