import LRA.Set.Constructions.ZFCSet.Axioms.Extensionality.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.EmptySet.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.Pairing.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.Union.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.PowerSet.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.Infinity.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.Separation.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.Replacement.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.Foundation.Axiom
import LRA.Set.Constructions.ZFCSet.Axioms.Choice.Axiom
