import LRA.Set.Constructions.ZFCSet.Axioms.Common
import LRA.Set.Constructions.ZFCSet.Axioms.EmptySet.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.Pairing.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.Union.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.PowerSet.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.Separation.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.Replacement.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.Infinity.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.Foundation.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.Choice.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.RelativeComplement.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.Intersection.Definitions
import LRA.Set.Constructions.ZFCSet.Axioms.SymmetricDifference.Definitions
