import LRA.AlgebraicStructures.LinearlyOrderedRing.Examples.Integers
import LRA.AlgebraicStructures.LinearlyOrderedRing.Examples.Rationals
import LRA.AlgebraicStructures.LinearlyOrderedRing.Examples.Reals
