import LRA.AlgebraicStructures.AdditiveMonoid.Examples.NaturalNumbersWithZero
import LRA.AlgebraicStructures.AdditiveMonoid.Examples.NonNegativeReals
import LRA.AlgebraicStructures.AdditiveMonoid.Examples.ExtendedReals
import LRA.AlgebraicStructures.AdditiveMonoid.Examples.SquareMatricesUnderAddition
