import LRA.AlgebraicStructures.CommutativeSemiring.Examples.NaturalNumbers
import LRA.AlgebraicStructures.CommutativeSemiring.Examples.NonNegativeReals
import LRA.AlgebraicStructures.CommutativeSemiring.Examples.ExtendedReals
