import LRA.AlgebraicStructures.AdditiveSemigroup.Interface.Laws.Definition
import LRA.UniversalAlgebra.InterpretedOperationBundles

namespace LRA.AlgebraicStructures

abbrev AdditiveSemigroupConceptSignature :=
  LRA.UniversalAlgebra.InterpretedOperationBundles.AdditiveOperationBundle

end LRA.AlgebraicStructures
