import LRA.AlgebraicStructures.CommutativeSemigroup.Examples.PositiveIntegersUnderAddition
import LRA.AlgebraicStructures.CommutativeSemigroup.Examples.Semilattices
import LRA.AlgebraicStructures.CommutativeSemigroup.Examples.PositiveEvenNaturalsUnderMultiplication
import LRA.AlgebraicStructures.CommutativeSemigroup.Examples.MinMaxOnReals
