import LRA.AlgebraicStructures.AbelianGroup.Interface.Definitions.Signature

namespace LRA.AlgebraicStructures.AbelianGroup.Interface.ModelTheory

end LRA.AlgebraicStructures.AbelianGroup.Interface.ModelTheory
