import LRA.Logic.Language.FirstOrder.Signature

/-!
First-order signature data for Presburger arithmetic.

The signature is the source-facing `\{0,S,+,<\}` Presburger language.  Equality
is logical equality, not a nonlogical relation symbol.
-/

namespace LRA.NumberSystems.PeanoSystems

/--
`PresburgerFunctionSymbol` is generated by the displayed constructors for presburger function symbol.

Logical form:

```lean
inductive PresburgerFunctionSymbol where
  | successor
  | addition
```
-/
inductive PresburgerFunctionSymbol where
  | successor
  | addition

/--
`PresburgerRelationSymbol` is generated by the displayed constructors for presburger relation symbol.

Logical form:

```lean
inductive PresburgerRelationSymbol where
  | lessThan
```
-/
inductive PresburgerRelationSymbol where
  | lessThan

/--
`PresburgerConstantSymbol` is generated by the displayed constructors for presburger constant symbol.

Logical form:

```lean
inductive PresburgerConstantSymbol where
  | zero
```
-/
inductive PresburgerConstantSymbol where
  | zero

/--
`PresburgerFunctions` defines the displayed object for presburger functions.

Logical form:

```lean
def PresburgerFunctions : LRA.Logic.ArityIndexedSymbols where
  Symbol := PresburgerFunctionSymbol
  arity
    | .successor => 1
    | .addition => 2
```
-/
def PresburgerFunctions : LRA.Logic.ArityIndexedSymbols where
  Symbol := PresburgerFunctionSymbol
  arity
    | .successor => 1
    | .addition => 2

/--
`PresburgerRelations` defines the displayed object for presburger relations.

Logical form:

```lean
def PresburgerRelations : LRA.Logic.ArityIndexedSymbols where
  Symbol := PresburgerRelationSymbol
  arity
    | .lessThan => 2
```
-/
def PresburgerRelations : LRA.Logic.ArityIndexedSymbols where
  Symbol := PresburgerRelationSymbol
  arity
    | .lessThan => 2

/- Volume II label: def:presburger-signature
   Lean declaration: LRA.NumberSystems.PeanoSystems.PresburgerSignature
   Status: pending -/
/--
`PresburgerSignature` defines the displayed object for presburger signature.

Logical form:

```lean
def PresburgerSignature : LRA.Logic.Signature where
  Functions := PresburgerFunctions
  Relations := PresburgerRelations
  Constants := PresburgerConstantSymbol
```
-/
def PresburgerSignature : LRA.Logic.Signature where
  Functions := PresburgerFunctions
  Relations := PresburgerRelations
  Constants := PresburgerConstantSymbol

end LRA.NumberSystems.PeanoSystems
