import LRA.AlgebraicStructures.CompleteOrderedField.Definition
import LRA.AlgebraicStructures.CompleteOrderedField.Interface.Signature.Definition
import LRA.AlgebraicStructures.CompleteOrderedField.Interface.ModelTheory.Model
import LRA.AlgebraicStructures.CompleteOrderedField.Interface.ModelTheory.Axioms
import LRA.AlgebraicStructures.CompleteOrderedField.Interface.ModelTheory.Satisfaction
import LRA.AlgebraicStructures.CompleteOrderedField.Theorems
import LRA.AlgebraicStructures.CompleteOrderedField.Characterizations
import LRA.AlgebraicStructures.CompleteOrderedField.Consequences
import LRA.AlgebraicStructures.CompleteOrderedField.Relationships

/-! Canonical import route for complete ordered fields. -/
