import LRA.SetSystems.SigmaAlgebra

namespace LRA.SetSystems

open LRA.Set

universe u v

variable {Element : Type u} {SetObject : Type v}
variable [Membership Element SetObject]
variable [Union SetObject] [Inter SetObject] [SDiff SetObject]
variable [EmptyCollection SetObject] [HasSubset SetObject]
variable [HasSymmDiff SetObject]
variable [HasCountableUnion SetObject]

/-- The collection underlying the sigma-algebra generated by `generator`.

This is the intersection predicate: an object belongs exactly when it belongs to
every sigma-algebra on `ambient` that contains every generator.

Logical form:

```lean
def GeneratedSigmaAlgebraCollection
    (ambient : SetObject) (generator : SetObject → Prop) : SetObject → Prop :=
  fun A =>
    ∀ sigma : SigmaAlgebraOfSets ambient,
      (∀ G, generator G → sigma.IsMember G) → sigma.IsMember A
```
-/
def GeneratedSigmaAlgebraCollection
    (ambient : SetObject) (generator : SetObject → Prop) :
    SetObject → Prop :=
  fun A =>
    ∀ sigma : SigmaAlgebraOfSets ambient,
      (∀ G, generator G → sigma.IsMember G) → sigma.IsMember A

/-- A generator family is admissible on `ambient` when at least one
sigma-algebra on `ambient` contains every generator.

This nonvacuity condition is load-bearing for interpreting
`GeneratedSigmaAlgebraCollection` as an actual intersection of containing
sigma-algebras.

Logical form:

```lean
def GeneratorAdmissible
    (ambient : SetObject) (generator : SetObject → Prop) : Prop :=
  ∃ sigma : SigmaAlgebraOfSets ambient,
    ∀ G, generator G → sigma.IsMember G
```
-/
def GeneratorAdmissible
    (ambient : SetObject) (generator : SetObject → Prop) : Prop :=
  ∃ sigma : SigmaAlgebraOfSets ambient,
    ∀ G, generator G → sigma.IsMember G

/-- Every member of the generated collection is contained in the ambient set,
provided the generators are admissible on that ambient set.

Logical form:

```lean
theorem GeneratedSigmaAlgebraMembersAreSubsets
    (ambient : SetObject) (generator : SetObject → Prop)
    (admissible : GeneratorAdmissible ambient generator) :
    ∀ A, GeneratedSigmaAlgebraCollection ambient generator A → A ⊆ ambient
```
-/
theorem GeneratedSigmaAlgebraMembersAreSubsets
    (ambient : SetObject) (generator : SetObject → Prop)
    (admissible : GeneratorAdmissible ambient generator) :
    ∀ A, GeneratedSigmaAlgebraCollection ambient generator A →
      A ⊆ ambient := by
  sorry


theorem GeneratedSigmaAlgebraEmptyIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    GeneratedSigmaAlgebraCollection ambient generator (∅ : SetObject) := by
  sorry


theorem GeneratedSigmaAlgebraUnionIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A B,
      GeneratedSigmaAlgebraCollection ambient generator A →
      GeneratedSigmaAlgebraCollection ambient generator B →
      GeneratedSigmaAlgebraCollection ambient generator (A ∪ B) := by
  sorry


theorem GeneratedSigmaAlgebraIntersectionIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A B,
      GeneratedSigmaAlgebraCollection ambient generator A →
      GeneratedSigmaAlgebraCollection ambient generator B →
      GeneratedSigmaAlgebraCollection ambient generator (A ∩ B) := by
  sorry


theorem GeneratedSigmaAlgebraDifferenceIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A B,
      GeneratedSigmaAlgebraCollection ambient generator A →
      GeneratedSigmaAlgebraCollection ambient generator B →
      GeneratedSigmaAlgebraCollection ambient generator (A \ B) := by
  sorry


theorem GeneratedSigmaAlgebraSymmetricDifferenceIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ A B,
      GeneratedSigmaAlgebraCollection ambient generator A →
      GeneratedSigmaAlgebraCollection ambient generator B →
      GeneratedSigmaAlgebraCollection ambient generator (A ∆ B) := by
  sorry


theorem GeneratedSigmaAlgebraAmbientIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    GeneratedSigmaAlgebraCollection ambient generator ambient := by
  sorry


theorem GeneratedSigmaAlgebraCountableUnionIsMember
    (ambient : SetObject) (generator : SetObject → Prop) :
    ∀ family : Nat → SetObject,
      (∀ index, GeneratedSigmaAlgebraCollection ambient generator
        (family index)) →
        GeneratedSigmaAlgebraCollection ambient generator
          (HasCountableUnion.countableUnion family) := by
  sorry

/-- The smallest sigma-algebra on `ambient` admitting every generator, under an
explicit certificate that such a containing sigma-algebra exists.

Logical form:

```lean
def GeneratedSigmaAlgebra
    (ambient : SetObject) (generator : SetObject → Prop)
    (admissible : GeneratorAdmissible ambient generator) :
    SigmaAlgebraOfSets ambient
```
-/
def GeneratedSigmaAlgebra
    (ambient : SetObject) (generator : SetObject → Prop)
    (admissible : GeneratorAdmissible ambient generator) :
    SigmaAlgebraOfSets ambient where
  IsMember := GeneratedSigmaAlgebraCollection ambient generator
  MembersAreSubsets :=
    GeneratedSigmaAlgebraMembersAreSubsets ambient generator admissible
  EmptyIsMember := GeneratedSigmaAlgebraEmptyIsMember ambient generator
  UnionIsMember := GeneratedSigmaAlgebraUnionIsMember ambient generator
  IntersectionIsMember :=
    GeneratedSigmaAlgebraIntersectionIsMember ambient generator
  DifferenceIsMember := GeneratedSigmaAlgebraDifferenceIsMember ambient generator
  SymmetricDifferenceIsMember :=
    GeneratedSigmaAlgebraSymmetricDifferenceIsMember ambient generator
  AmbientIsMember := GeneratedSigmaAlgebraAmbientIsMember ambient generator
  CountableUnionIsMember :=
    GeneratedSigmaAlgebraCountableUnionIsMember ambient generator

/-- Every generator belongs to the generated sigma-algebra.

Logical form:

```lean
theorem GeneratedSigmaAlgebraContainsGenerator
    (ambient : SetObject) (generator : SetObject → Prop)
    (admissible : GeneratorAdmissible ambient generator)
    (G : SetObject) (GIsGenerator : generator G) :
    (GeneratedSigmaAlgebra ambient generator admissible).IsMember G
```
-/
theorem GeneratedSigmaAlgebraContainsGenerator
    (ambient : SetObject) (generator : SetObject → Prop)
    (admissible : GeneratorAdmissible ambient generator)
    (G : SetObject) (GIsGenerator : generator G) :
    (GeneratedSigmaAlgebra ambient generator admissible).IsMember G := by
  sorry

/-- The generated sigma-algebra is contained in every sigma-algebra on the same
ambient set that contains all generators.

Logical form:

```lean
theorem GeneratedSigmaAlgebraMinimal
    (ambient : SetObject) (generator : SetObject → Prop)
    (admissible : GeneratorAdmissible ambient generator)
    (sigma : SigmaAlgebraOfSets ambient)
    (sigmaAdmitsGenerators : ∀ G, generator G → sigma.IsMember G) :
    ∀ A, (GeneratedSigmaAlgebra ambient generator admissible).IsMember A →
      sigma.IsMember A
```
-/
theorem GeneratedSigmaAlgebraMinimal
    (ambient : SetObject) (generator : SetObject → Prop)
    (admissible : GeneratorAdmissible ambient generator)
    (sigma : SigmaAlgebraOfSets ambient)
    (sigmaAdmitsGenerators : ∀ G, generator G → sigma.IsMember G) :
    ∀ A, (GeneratedSigmaAlgebra ambient generator admissible).IsMember A →
      sigma.IsMember A := by
  sorry

/-- Temporary topology-facing specialization. The supplied admissibility
certificate says that at least one sigma-algebra on `ambient` contains all
open-set generators. This definition should move to `Topology/Borel` when that
subject is standardized.

Logical form:

```lean
def BorelSigmaAlgebra
    (ambient : SetObject) (opens : SetObject → Prop)
    (opensAdmissible : GeneratorAdmissible ambient opens) :
    SigmaAlgebraOfSets ambient :=
  GeneratedSigmaAlgebra ambient opens opensAdmissible
```
-/
def BorelSigmaAlgebra
    (ambient : SetObject) (opens : SetObject → Prop)
    (opensAdmissible : GeneratorAdmissible ambient opens) :
    SigmaAlgebraOfSets ambient :=
  GeneratedSigmaAlgebra ambient opens opensAdmissible

end LRA.SetSystems
