import Mathlib.Data.Real.Basic
import LRA.VolumeI.Set.Implementations.LRASet.Algebra.SigmaAlgebraProperties

namespace LRA.VolumeI.Set.Implementations.LRASet

/-- A topology on `Alpha` is a family of subsets containing the empty and
universal sets, closed under arbitrary unions, and closed under finite
intersections. -/
def TopologyOn {Alpha : LRACarrier}
    (Collection : SetCollection Alpha) : Prop :=
  LRASet.Member (LRASet.Empty Alpha) Collection ∧
    LRASet.Member (LRASet.Universal Alpha) Collection ∧
      ClosedUnderArbitraryUnions Collection ∧
        ClosedUnderFiniteIntersections Collection

/-- The Borel sigma-algebra generated by a topology's open-set family. -/
def BorelSigmaAlgebra {Alpha : LRACarrier}
    (Topology : SetCollection Alpha) : SetCollection Alpha :=
  GeneratedSigmaAlgebra Topology

/-- Every open set is Borel. -/
theorem TopologySubsetBorelSigmaAlgebra {Alpha : LRACarrier}
    (Topology : SetCollection Alpha) :
    LRASet.Subset Topology (BorelSigmaAlgebra Topology) := by
  sorry

/-- The Borel family generated by a topology is a sigma-algebra. -/
theorem BorelSigmaAlgebraIsSigmaAlgebra {Alpha : LRACarrier}
    (Topology : SetCollection Alpha) :
    SigmaAlgebra (BorelSigmaAlgebra Topology) := by
  sorry

/-- The Borel sigma-algebra is contained in every sigma-algebra containing the
open-set family. -/
theorem BorelSigmaAlgebraMinimal {Alpha : LRACarrier}
    (Topology Candidate : SetCollection Alpha)
    (CandidateSigma : SigmaAlgebra Candidate)
    (TopologySubsetCandidate : LRASet.Subset Topology Candidate) :
    LRASet.Subset (BorelSigmaAlgebra Topology) Candidate := by
  sorry

/-- A real-valued distance function on a carrier. -/
abbrev DistanceFunction (Alpha : LRACarrier) :=
  Alpha → Alpha → Real

/-- A distance function is a metric when it satisfies nonnegativity,
identity of indiscernibles, symmetry, and the triangle inequality. -/
def MetricOn {Alpha : LRACarrier}
    (Distance : DistanceFunction Alpha) : Prop :=
  (∀ Left Right : Alpha, 0 ≤ Distance Left Right) ∧
    (∀ Left Right : Alpha, Distance Left Right = 0 ↔ Left = Right) ∧
      (∀ Left Right : Alpha, Distance Left Right = Distance Right Left) ∧
        (∀ Left Middle Right : Alpha,
          Distance Left Right ≤ Distance Left Middle + Distance Middle Right)

/-- The open ball with center `Center` and radius `Radius` determined by a
distance function. -/
def MetricOpenBall {Alpha : LRACarrier}
    (Distance : DistanceFunction Alpha)
    (Center : Alpha) (Radius : Real) : LRASet Alpha :=
  fun Point => Distance Center Point < Radius

/-- A set is open for a distance function when every point in it contains a
positive-radius open ball contained in the set. -/
def MetricOpenSet {Alpha : LRACarrier}
    (Distance : DistanceFunction Alpha)
    (SetObject : LRASet Alpha) : Prop :=
  ∀ Center : Alpha,
    LRASet.Member Center SetObject →
      ∃ Radius : Real,
        0 < Radius ∧
          LRASet.Subset (MetricOpenBall Distance Center Radius) SetObject

/-- The metric topology induced by a distance function is the family of
distance-open sets. -/
def MetricTopology {Alpha : LRACarrier}
    (Distance : DistanceFunction Alpha) : SetCollection Alpha :=
  fun SetObject => MetricOpenSet Distance SetObject

/-- The coordinate carrier for finite-dimensional Euclidean space `ℝⁿ`. -/
abbrev EuclideanSpace (Dimension : Nat) :=
  Fin Dimension → Real

/-- The Borel sigma-algebra on finite-dimensional Euclidean space generated by
the metric topology of a chosen Euclidean distance function. -/
def BorelSigmaAlgebraRn
    (Dimension : Nat)
    (EuclideanDistance : DistanceFunction (EuclideanSpace Dimension)) :
    SetCollection (EuclideanSpace Dimension) :=
  BorelSigmaAlgebra (MetricTopology EuclideanDistance)

end LRA.VolumeI.Set.Implementations.LRASet
