-- LRA/NumberSystems/IntegerStructure/Bundled.lean
-- A self-contained (non-`Element`/`SetObject`-generic) presentation of the
-- two-sided successor/predecessor axioms, with categoricity proved
-- concretely against Lean's built-in `Int`.

namespace LRA.NumberSystems.IntegerStructure.Bundled

/-!
Volume II label: integers-polish-discrete-integer-structure
Verification status: experimental statement/proof work

This module formalizes the abstract `(Z1)`--`(Z3)` integer-structure axioms:

* successor and predecessor are mutual inverses,
* positive successor iterates of zero are aperiodic,
* two-sided induction holds.

The intended theorem is categoricity: every such structure is represented by
the built-in `Int` through the unique walk generated by `succ` and `pred`.

Moved from `LRA.VolumeII.Integers.Polish.DiscreteIntegerStructure` (no
change to its proofs). This module bundles its carrier as a plain field
(`carrier : Type u`) rather than taking `Element`/`SetObject` as external
parameters, so it sits alongside -- not inside -- the `Element`/`SetObject`-
generic presentation in `IntegerStructure.Definition`/`.Categoricity`, the
way `NModel` sits alongside `PeanoSystem.PeanoSystem`: a second, self-
contained presentation of the same idea, proved here concretely against
`Int` rather than model-to-model. Unifying the two is tracked in
`Integers/ProofOrder.md`.
-/

/--
**[Def — iterate]**

Logical form:

```lean
def iterate {α : Type u} (f : α → α) : Nat → α → α
  | 0, x => x
  | n + 1, x => f (iterate f n x)
```
-/
def iterate {α : Type u} (f : α → α) : Nat → α → α
  | 0, x => x
  | n + 1, x => f (iterate f n x)

/--
**[Theorem — iterate_succ]**

Logical form:

```lean
theorem iterate_succ' {α : Type u} (f : α → α) (n : Nat) (x : α) :
    iterate f (n + 1) x = f (iterate f n x)
```
-/
theorem iterate_succ' {α : Type u} (f : α → α) (n : Nat) (x : α) :
    iterate f (n + 1) x = f (iterate f n x) := by
  sorry

/--
**[Theorem — iterate_comm]**

Logical form:

```lean
theorem iterate_comm {α : Type u} (f : α → α) (n : Nat) (x : α) :
    f (iterate f n x) = iterate f n (f x)
```
-/
theorem iterate_comm {α : Type u} (f : α → α) (n : Nat) (x : α) :
    f (iterate f n x) = iterate f n (f x) := by
  sorry

/--
**[Theorem — iterate_succ_apply]**

Logical form:

```lean
theorem iterate_succ_apply {α : Type u} (f : α → α) (n : Nat) (x : α) :
    iterate f (n + 1) x = iterate f n (f x)
```
-/
theorem iterate_succ_apply {α : Type u} (f : α → α) (n : Nat) (x : α) :
    iterate f (n + 1) x = iterate f n (f x) := by
  sorry

/--
**[Theorem — iterate_add]**

Logical form:

```lean
theorem iterate_add {α : Type u} (f : α → α) (m n : Nat) (x : α) :
    iterate f (m + n) x = iterate f m (iterate f n x)
```
-/
theorem iterate_add {α : Type u} (f : α → α) (m n : Nat) (x : α) :
    iterate f (m + n) x = iterate f m (iterate f n x) := by
  sorry

/--
**[Def — Injective]**

Logical form:

```lean
```
-/
def Injective {α β : Type _} (f : α → β) : Prop :=
  ∀ ⦃a b⦄, f a = f b → a = b

/--
**[Def — Surjective]**

Logical form:

```lean
```
-/
def Surjective {α β : Type _} (f : α → β) : Prop :=
  ∀ b, ∃ a, f a = b

/--
**[Def — Bijective]**

Logical form:

```lean
```
-/
def Bijective {α β : Type _} (f : α → β) : Prop :=
  Injective f ∧ Surjective f

/--
**[Structure — IntegerStructure]**

Logical form:

```lean
structure IntegerStructure where
  carrier : Type u
  zero : carrier
  succ : carrier → carrier
  pred : carrier → carrier
  pred_succ : ∀ x, pred (succ x) = x
  succ_pred : ∀ x, succ (pred x) = x
  aperiodic : ∀ n : Nat, 0 < n → iterate succ n zero ≠ zero
  induction :
    ∀ (A : carrier → Prop),
      A zero →
      (∀ x, A x → A (succ x)) →
      (∀ x, A x → A (pred x)) →
      ∀ x, A x
```
-/
structure IntegerStructure where
  carrier : Type u
  zero : carrier
  succ : carrier → carrier
  pred : carrier → carrier
  pred_succ : ∀ x, pred (succ x) = x
  succ_pred : ∀ x, succ (pred x) = x
  aperiodic : ∀ n : Nat, 0 < n → iterate succ n zero ≠ zero
  induction :
    ∀ (A : carrier → Prop),
      A zero →
      (∀ x, A x → A (succ x)) →
      (∀ x, A x → A (pred x)) →
      ∀ x, A x

end LRA.NumberSystems.IntegerStructure.Bundled
namespace LRA.NumberSystems.IntegerStructure.Bundled.IntegerStructure

variable (S : IntegerStructure)

/--
**[Def — rep]**

Logical form:

```lean
def rep : Int → S.carrier
  | Int.ofNat n => iterate S.succ n S.zero
  | Int.negSucc n => iterate S.pred (n + 1) S.zero
```
-/
def rep : Int → S.carrier
  | Int.ofNat n => iterate S.succ n S.zero
  | Int.negSucc n => iterate S.pred (n + 1) S.zero

/--
`rep_zero` states rep zero.

Logical form:

```lean
theorem rep_zero : S.rep 0 = S.zero
```
-/
@[simp] theorem rep_zero : S.rep 0 = S.zero := by
  sorry

/--
**[Theorem — pred_iterate_succ_iterate]**

Logical form:

```lean
theorem pred_iterate_succ_iterate (n : Nat) (x : S.carrier) :
    iterate S.pred n (iterate S.succ n x) = x
```
-/
theorem pred_iterate_succ_iterate (n : Nat) (x : S.carrier) :
    iterate S.pred n (iterate S.succ n x) = x := by
  sorry

/--
**[Theorem — succ_iterate_pred_iterate]**

Logical form:

```lean
theorem succ_iterate_pred_iterate (n : Nat) (x : S.carrier) :
    iterate S.succ n (iterate S.pred n x) = x
```
-/
theorem succ_iterate_pred_iterate (n : Nat) (x : S.carrier) :
    iterate S.succ n (iterate S.pred n x) = x := by
  sorry

/--
**[Theorem — aperiodic_pred]**

Logical form:

```lean
theorem aperiodic_pred (n : Nat) (h : 0 < n) :
    iterate S.pred n S.zero ≠ S.zero
```
-/
theorem aperiodic_pred (n : Nat) (h : 0 < n) :
    iterate S.pred n S.zero ≠ S.zero := by
  sorry

/--
**[Theorem — iterate_succ_injective]**

Logical form:

```lean
theorem iterate_succ_injective (n : Nat) : Injective (iterate S.succ n)
```
-/
theorem iterate_succ_injective (n : Nat) :
    _root_.Function.Injective (iterate S.succ n) := by
  sorry

/--
**[Theorem — iterate_pred_injective]**

Logical form:

```lean
theorem iterate_pred_injective (n : Nat) : Injective (iterate S.pred n)
```
-/
theorem iterate_pred_injective (n : Nat) :
    _root_.Function.Injective (iterate S.pred n) := by
  sorry

/--
**[Theorem — no_forward_collision]**

Logical form:

```lean
theorem no_forward_collision
    (m n : Nat)
    (h : iterate S.succ m S.zero = iterate S.succ n S.zero) :
    m = n
```
-/
theorem no_forward_collision
    (m n : Nat)
    (h : iterate S.succ m S.zero = iterate S.succ n S.zero) :
    m = n := by
  sorry

/--
**[Theorem — no_backward_collision]**

Logical form:

```lean
theorem no_backward_collision
    (m n : Nat)
    (h : iterate S.pred m S.zero = iterate S.pred n S.zero) :
    m = n
```
-/
theorem no_backward_collision
    (m n : Nat)
    (h : iterate S.pred m S.zero = iterate S.pred n S.zero) :
    m = n := by
  sorry

/--
**[Theorem — no_mixed_collision]**

Logical form:

```lean
theorem no_mixed_collision
    (m n : Nat)
    (h : iterate S.succ m S.zero = iterate S.pred (n + 1) S.zero) :
    False
```
-/
theorem no_mixed_collision
    (m n : Nat)
    (h : iterate S.succ m S.zero = iterate S.pred (n + 1) S.zero) :
    False := by
  sorry

/--
**[Theorem — rep_injective]**

Logical form:

```lean
theorem rep_injective : Injective S.rep
```
-/
theorem rep_injective : _root_.Function.Injective S.rep := by
  sorry

/--
**[Theorem — rep_succ]**

Logical form:

```lean
theorem rep_succ (n : Int) : S.rep (n + 1) = S.succ (S.rep n)
```
-/
theorem rep_succ (n : Int) : S.rep (n + 1) = S.succ (S.rep n) := by
  sorry

/--
**[Theorem — rep_pred]**

Logical form:

```lean
theorem rep_pred (n : Int) : S.rep (n - 1) = S.pred (S.rep n)
```
-/
theorem rep_pred (n : Int) : S.rep (n - 1) = S.pred (S.rep n) := by
  sorry

/--
**[Theorem — rep_surjective]**

Logical form:

```lean
theorem rep_surjective : Surjective S.rep
```
-/
theorem rep_surjective : _root_.Function.Surjective S.rep := by
  sorry

/--
**[Theorem — rep_bijective]**

Logical form:

```lean
theorem rep_bijective : Bijective S.rep
```
-/
theorem rep_bijective :
    _root_.Function.Injective S.rep ∧ _root_.Function.Surjective S.rep := by
  sorry

/--
**[Theorem — categoricity]**

Logical form:

```lean
theorem categoricity :
    _root_.Function.Bijective S.rep ∧
      S.rep 0 = S.zero ∧
      ∀ n : Int, S.rep (n + 1) = S.succ (S.rep n)
```
-/
theorem categoricity :
    (_root_.Function.Injective S.rep ∧ _root_.Function.Surjective S.rep) ∧
      S.rep 0 = S.zero ∧
      ∀ n : Int, S.rep (n + 1) = S.succ (S.rep n) := by
  sorry

end LRA.NumberSystems.IntegerStructure.Bundled.IntegerStructure
namespace LRA.NumberSystems.IntegerStructure.Bundled

end LRA.NumberSystems.IntegerStructure.Bundled
