import LRA.Relation.Definition

namespace LRA.Relation

universe u

/-- The transitive closure of a relation: the relation generated by one-step
edges and closed under concatenation. -/
inductive TransitiveClosure {Alpha : Type u}
    (relation : Endorelation Alpha) : Endorelation Alpha
  | base {left right : Alpha} :
      relation left right → TransitiveClosure relation left right
  | trans {left middle right : Alpha} :
      TransitiveClosure relation left middle →
      TransitiveClosure relation middle right →
      TransitiveClosure relation left right

end LRA.Relation
