import LRA.AlgebraicStructures.CommutativeMonoid.Examples.NaturalNumbersUnderAddition
import LRA.AlgebraicStructures.CommutativeMonoid.Examples.NaturalNumbersUnderMultiplication
import LRA.AlgebraicStructures.CommutativeMonoid.Examples.PowerSetUnderUnion
import LRA.AlgebraicStructures.CommutativeMonoid.Examples.BooleanConjunction
